export enum Ability {
  DEFAULT = "DEFAULT",
  FIRE_BLAST = "FIRE_BLAST",
  WHEEL_OF_FIRE = "WHEEL_OF_FIRE",
  SEISMIC_TOSS = "SEISMIC_TOSS",
  GUILLOTINE = "GUILLOTINE",
  ROCK_SLIDE = "ROCK_SLIDE",
  HEAT_WAVE = "HEAT_WAVE",
  THUNDER = "THUNDER",
  HYDRO_PUMP = "HYDRO_PUMP",
  DRACO_METEOR = "DRACO_METEOR",
  BLAZE_KICK = "BLAZE_KICK",
  WISH = "WISH",
  CALM_MIND = "CALM_MIND",
  IRON_DEFENSE = "IRON_DEFENSE",
  METRONOME = "METRONOME",
  SOAK = "SOAK",
  IRON_TAIL = "IRON_TAIL",
  BLAST_BURN = "BLAST_BURN",
  CHARGE = "CHARGE",
  DISCHARGE = "DISCHARGE",
  BITE = "BITE",
  DRAGON_TAIL = "DRAGON_TAIL",
  DRAGON_BREATH = "DRAGON_BREATH",
  ICICLE_CRASH = "ICICLE_CRASH",
  ROOT = "ROOT",
  TORMENT = "TORMENT",
  STOMP = "STOMP",
  PAYBACK = "PAYBACK",
  NIGHT_SLASH = "NIGHT_SLASH",
  BUG_BUZZ = "BUG_BUZZ",
  STRING_SHOT = "STRING_SHOT",
  VENOSHOCK = "VENOSHOCK",
  LEECH_LIFE = "LEECH_LIFE",
  HAPPY_HOUR = "HAPPY_HOUR",
  TELEPORT = "TELEPORT",
  NASTY_PLOT = "NASTY_PLOT",
  THIEF = "THIEF",
  STUN_SPORE = "STUN_SPORE",
  METEOR_MASH = "METEOR_MASH",
  HURRICANE = "HURRICANE",
  BURN = "BURN",
  SILENCE = "SILENCE",
  SLEEP = "SLEEP",
  FREEZE = "FREEZE",
  PROTECT = "PROTECT",
  POISON = "POISON",
  CONFUSION = "CONFUSION",
  ORIGIN_PULSE = "ORIGIN_PULSE",
  SEED_FLARE = "SEED_FLARE",
  HEAL_BLOCK = "HEAL_BLOCK",
  ROAR_OF_TIME = "ROAR_OF_TIME",
  ROCK_TOMB = "ROCK_TOMB",
  ROCK_SMASH = "ROCK_SMASH",
  HEAD_SMASH = "HEAD_SMASH",
  VOLT_SWITCH = "VOLT_SWITCH",
  SHADOW_CLONE = "SHADOW_CLONE",
  HYPER_VOICE = "HYPER_VOICE",
  PETAL_DANCE = "PETAL_DANCE",
  ECHO = "ECHO",
  TRI_ATTACK = "TRI_ATTACK",
  GRASS_WHISTLE = "GRASS_WHISTLE",
  HIGH_JUMP_KICK = "HIGH_JUMP_KICK",
  DISARMING_VOICE = "DISARMING_VOICE",
  RELIC_SONG = "RELIC_SONG",
  GROWL = "GROWL",
  BONEMERANG = "BONEMERANG",
  CLANGOROUS_SOUL = "CLANGOROUS_SOUL",
  NIGHTMARE = "NIGHTMARE",
  EXPLOSION = "EXPLOSION",
  KING_SHIELD = "KING_SHIELD",
  CORRUPTED_NATURE = "CORRUPTED_NATURE",
  CRABHAMMER = "CRABHAMMER",
  DIAMOND_STORM = "DIAMOND_STORM",
  DRACO_ENERGY = "DRACO_ENERGY",
  DYNAMAX_CANNON = "DYNAMAX_CANNON",
  DYNAMIC_PUNCH = "DYNAMIC_PUNCH",
  ELECTRO_BOOST = "ELECTRO_BOOST",
  ELECTRO_WEB = "ELECTRO_WEB",
  FIRE_TRICK = "FIRE_TRICK",
  FLAME_CHARGE = "FLAME_CHARGE",
  LEECH_SEED = "LEECH_SEED",
  LOCK_ON = "LOCK_ON",
  PSYCH_UP = "PSYCH_UP",
  RAZOR_WIND = "RAZOR_WIND",
  TWISTING_NETHER = "TWISTING_NETHER",
  WONDER_GUARD = "WONDER_GUARD",
  SONG_OF_DESIRE = "SONG_OF_DESIRE",
  CONFUSING_MIND = "CONFUSING_MIND",
  KNOWLEDGE_THIEF = "KNOWLEDGE_THIEF",
  EARTHQUAKE = "EARTHQUAKE",
  SOFT_BOILED = "SOFT_BOILED",
  ELECTRIC_SURGE = "ELECTRIC_SURGE",
  PSYCHIC_SURGE = "PSYCHIC_SURGE",
  MIND_BLOWN = "MIND_BLOWN",
  PAYDAY = "PAYDAY",
  BEAT_UP = "BEAT_UP",
  BLUE_FLARE = "BLUE_FLARE",
  FUSION_BOLT = "FUSION_BOLT",
  AURORA_VEIL = "AURORA_VEIL",
  AQUA_JET = "AQUA_JET",
  JUDGEMENT = "JUDGEMENT",
  CHATTER = "CHATTER",
  LIQUIDATION = "LIQUIDATION",
  STEAM_ERUPTION = "STEAM_ERUPTION",
  APPLE_ACID = "APPLE_ACID",
  SHADOW_BALL = "SHADOW_BALL",
  DIVE = "DIVE",
  SPIKE_ARMOR = "SPIKE_ARMOR",
  FUTURE_SIGHT = "FUTURE_SIGHT",
  FAKE_TEARS = "FAKE_TEARS",
  SPARKLING_ARIA = "SPARKLING_ARIA",
  DRAGON_DARTS = "DRAGON_DARTS",
  GRASSY_SURGE = "GRASSY_SURGE",
  MISTY_SURGE = "MISTY_SURGE",
  SKY_ATTACK = "SKY_ATTACK",
  ILLUSION = "ILLUSION",
  SMOG = "SMOG",
  AURORA_BEAM = "AURORA_BEAM",
  AGILITY = "AGILITY",
  SPIRIT_SHACKLE = "SPIRIT_SHACKLE",
  WATER_SHURIKEN = "WATER_SHURIKEN",
  SHADOW_SNEAK = "SHADOW_SNEAK",
  MACH_PUNCH = "MACH_PUNCH",
  UPPERCUT = "UPPERCUT",
  TRIPLE_KICK = "TRIPLE_KICK",
  MAWASHI_GERI = "MAWASHI_GERI",
  FORECAST = "FORECAST",
  SACRED_SWORD = "SACRED_SWORD",
  X_SCISSOR = "X_SCISSOR",
  PLASMA_FIST = "PLASMA_FIST",
  SPECTRAL_THIEF = "SPECTRAL_THIEF",
  GEOMANCY = "GEOMANCY",
  DEATH_WING = "DEATH_WING",
  SLACK_OFF = "SLACK_OFF",
  DARK_VOID = "DARK_VOID",
  OVERHEAT = "OVERHEAT",
  HYPNOSIS = "HYPNOSIS",
  MIMIC = "MIMIC",
  HEX = "HEX",
  GROWTH = "GROWTH",
  HEAL_ORDER = "HEAL_ORDER",
  SHELL_TRAP = "SHELL_TRAP",
  DIG = "DIG",
  FIRE_SPIN = "FIRE_SPIN",
  SEARING_SHOT = "SEARING_SHOT",
  PECK = "PECK",
  SPLASH = "SPLASH",
  COUNTER = "COUNTER",
  COSMIC_POWER = "COSMIC_POWER",
  STICKY_WEB = "STICKY_WEB",
  SILVER_WIND = "SILVER_WIND",
  POISON_POWDER = "POISON_POWDER",
  ICY_WIND = "ICY_WIND",
  GIGATON_HAMMER = "GIGATON_HAMMER",
  ACROBATICS = "ACROBATICS",
  ABSORB = "ABSORB",
  ROLLOUT = "ROLLOUT",
  THRASH = "THRASH",
  SOLAR_BEAM = "SOLAR_BEAM",
  MAGMA_STORM = "MAGMA_STORM",
  SLASHING_CLAW = "SLASHING_CLAW",
  ERUPTION = "ERUPTION",
  MIST_BALL = "MIST_BALL",
  LUSTER_PURGE = "LUSTER_PURGE",
  MUD_BUBBLE = "MUD_BUBBLE",
  LINK_CABLE = "LINK_CABLE",
  MAGIC_BOUNCE = "MAGIC_BOUNCE",
  HIDDEN_POWER_A = "HIDDEN_POWER_A",
  HIDDEN_POWER_B = "HIDDEN_POWER_B",
  HIDDEN_POWER_C = "HIDDEN_POWER_C",
  HIDDEN_POWER_D = "HIDDEN_POWER_D",
  HIDDEN_POWER_E = "HIDDEN_POWER_E",
  HIDDEN_POWER_F = "HIDDEN_POWER_F",
  HIDDEN_POWER_G = "HIDDEN_POWER_G",
  HIDDEN_POWER_H = "HIDDEN_POWER_H",
  HIDDEN_POWER_I = "HIDDEN_POWER_I",
  HIDDEN_POWER_J = "HIDDEN_POWER_J",
  HIDDEN_POWER_K = "HIDDEN_POWER_K",
  HIDDEN_POWER_L = "HIDDEN_POWER_L",
  HIDDEN_POWER_M = "HIDDEN_POWER_M",
  HIDDEN_POWER_N = "HIDDEN_POWER_N",
  HIDDEN_POWER_O = "HIDDEN_POWER_O",
  HIDDEN_POWER_P = "HIDDEN_POWER_P",
  HIDDEN_POWER_Q = "HIDDEN_POWER_Q",
  HIDDEN_POWER_R = "HIDDEN_POWER_R",
  HIDDEN_POWER_S = "HIDDEN_POWER_S",
  HIDDEN_POWER_T = "HIDDEN_POWER_T",
  HIDDEN_POWER_U = "HIDDEN_POWER_U",
  HIDDEN_POWER_V = "HIDDEN_POWER_V",
  HIDDEN_POWER_W = "HIDDEN_POWER_W",
  HIDDEN_POWER_X = "HIDDEN_POWER_X",
  HIDDEN_POWER_Y = "HIDDEN_POWER_Y",
  HIDDEN_POWER_Z = "HIDDEN_POWER_Z",
  HIDDEN_POWER_QM = "HIDDEN_POWER_QM",
  HIDDEN_POWER_EM = "HIDDEN_POWER_EM",
  POISON_JAB = "POISON_JAB",
  SHELL_SMASH = "SHELL_SMASH"
}

export const CopyableAbility: { [key in Ability]: boolean } = {
  [Ability.DEFAULT]: true,
  [Ability.FIRE_BLAST]: true,
  [Ability.WHEEL_OF_FIRE]: true,
  [Ability.SEISMIC_TOSS]: true,
  [Ability.GUILLOTINE]: true,
  [Ability.ROCK_SLIDE]: true,
  [Ability.HEAT_WAVE]: true,
  [Ability.THUNDER]: true,
  [Ability.HYDRO_PUMP]: true,
  [Ability.DRACO_METEOR]: true,
  [Ability.BLAZE_KICK]: true,
  [Ability.WISH]: true,
  [Ability.CALM_MIND]: true,
  [Ability.IRON_DEFENSE]: true,
  [Ability.METRONOME]: true,
  [Ability.SOAK]: true,
  [Ability.IRON_TAIL]: true,
  [Ability.BLAST_BURN]: true,
  [Ability.CHARGE]: true,
  [Ability.DISCHARGE]: true,
  [Ability.BITE]: true,
  [Ability.DRAGON_TAIL]: true,
  [Ability.DRAGON_BREATH]: true,
  [Ability.ICICLE_CRASH]: true,
  [Ability.ROOT]: true,
  [Ability.TORMENT]: true,
  [Ability.STOMP]: true,
  [Ability.PAYBACK]: true,
  [Ability.NIGHT_SLASH]: true,
  [Ability.BUG_BUZZ]: true,
  [Ability.STRING_SHOT]: true,
  [Ability.VENOSHOCK]: true,
  [Ability.LEECH_LIFE]: true,
  [Ability.HAPPY_HOUR]: true,
  [Ability.TELEPORT]: true,
  [Ability.NASTY_PLOT]: true,
  [Ability.THIEF]: true,
  [Ability.STUN_SPORE]: true,
  [Ability.METEOR_MASH]: true,
  [Ability.HURRICANE]: true,
  [Ability.BURN]: true,
  [Ability.SILENCE]: true,
  [Ability.SLEEP]: true,
  [Ability.FREEZE]: true,
  [Ability.PROTECT]: true,
  [Ability.POISON]: true,
  [Ability.CONFUSION]: true,
  [Ability.ORIGIN_PULSE]: true,
  [Ability.SEED_FLARE]: true,
  [Ability.HEAL_BLOCK]: true,
  [Ability.ROAR_OF_TIME]: true,
  [Ability.ROCK_TOMB]: true,
  [Ability.ROCK_SMASH]: true,
  [Ability.HEAD_SMASH]: true,
  [Ability.VOLT_SWITCH]: true,
  [Ability.SHADOW_CLONE]: true,
  [Ability.HYPER_VOICE]: true,
  [Ability.PETAL_DANCE]: true,
  [Ability.ECHO]: true,
  [Ability.TRI_ATTACK]: true,
  [Ability.GRASS_WHISTLE]: true,
  [Ability.HIGH_JUMP_KICK]: true,
  [Ability.DISARMING_VOICE]: true,
  [Ability.RELIC_SONG]: true,
  [Ability.GROWL]: true,
  [Ability.BONEMERANG]: true,
  [Ability.CLANGOROUS_SOUL]: true,
  [Ability.NIGHTMARE]: true,
  [Ability.EXPLOSION]: true,
  [Ability.KING_SHIELD]: true,
  [Ability.CORRUPTED_NATURE]: true,
  [Ability.CRABHAMMER]: true,
  [Ability.DIAMOND_STORM]: true,
  [Ability.DRACO_ENERGY]: true,
  [Ability.DYNAMAX_CANNON]: true,
  [Ability.DYNAMIC_PUNCH]: true,
  [Ability.ELECTRO_BOOST]: true,
  [Ability.ELECTRO_WEB]: true,
  [Ability.FIRE_TRICK]: true,
  [Ability.FLAME_CHARGE]: true,
  [Ability.LEECH_SEED]: true,
  [Ability.LOCK_ON]: true,
  [Ability.PSYCH_UP]: true,
  [Ability.RAZOR_WIND]: true,
  [Ability.TWISTING_NETHER]: true,
  [Ability.WONDER_GUARD]: true,
  [Ability.SONG_OF_DESIRE]: true,
  [Ability.CONFUSING_MIND]: true,
  [Ability.KNOWLEDGE_THIEF]: false,
  [Ability.EARTHQUAKE]: true,
  [Ability.SOFT_BOILED]: true,
  [Ability.ELECTRIC_SURGE]: true,
  [Ability.PSYCHIC_SURGE]: true,
  [Ability.MIND_BLOWN]: true,
  [Ability.PAYDAY]: true,
  [Ability.BEAT_UP]: true,
  [Ability.BLUE_FLARE]: true,
  [Ability.FUSION_BOLT]: true,
  [Ability.AURORA_VEIL]: true,
  [Ability.AQUA_JET]: true,
  [Ability.JUDGEMENT]: true,
  [Ability.CHATTER]: true,
  [Ability.LIQUIDATION]: true,
  [Ability.STEAM_ERUPTION]: true,
  [Ability.APPLE_ACID]: true,
  [Ability.SHADOW_BALL]: true,
  [Ability.DIVE]: true,
  [Ability.SPIKE_ARMOR]: true,
  [Ability.FUTURE_SIGHT]: true,
  [Ability.FAKE_TEARS]: true,
  [Ability.SPARKLING_ARIA]: true,
  [Ability.DRAGON_DARTS]: true,
  [Ability.GRASSY_SURGE]: true,
  [Ability.MISTY_SURGE]: true,
  [Ability.SKY_ATTACK]: true,
  [Ability.ILLUSION]: true,
  [Ability.SMOG]: true,
  [Ability.AURORA_BEAM]: true,
  [Ability.AGILITY]: true,
  [Ability.SPIRIT_SHACKLE]: true,
  [Ability.WATER_SHURIKEN]: true,
  [Ability.SHADOW_SNEAK]: true,
  [Ability.MACH_PUNCH]: true,
  [Ability.UPPERCUT]: true,
  [Ability.TRIPLE_KICK]: true,
  [Ability.MAWASHI_GERI]: true,
  [Ability.FORECAST]: true,
  [Ability.SACRED_SWORD]: true,
  [Ability.X_SCISSOR]: true,
  [Ability.PLASMA_FIST]: true,
  [Ability.SPECTRAL_THIEF]: true,
  [Ability.GEOMANCY]: true,
  [Ability.DEATH_WING]: true,
  [Ability.SLACK_OFF]: true,
  [Ability.DARK_VOID]: true,
  [Ability.OVERHEAT]: true,
  [Ability.HYPNOSIS]: true,
  [Ability.MIMIC]: false,
  [Ability.HEX]: true,
  [Ability.GROWTH]: true,
  [Ability.HEAL_ORDER]: true,
  [Ability.SHELL_TRAP]: true,
  [Ability.DIG]: true,
  [Ability.FIRE_SPIN]: true,
  [Ability.SEARING_SHOT]: true,
  [Ability.PECK]: true,
  [Ability.SPLASH]: true,
  [Ability.COUNTER]: true,
  [Ability.COSMIC_POWER]: true,
  [Ability.STICKY_WEB]: true,
  [Ability.SILVER_WIND]: true,
  [Ability.POISON_POWDER]: true,
  [Ability.ICY_WIND]: true,
  [Ability.GIGATON_HAMMER]: true,
  [Ability.ACROBATICS]: true,
  [Ability.ABSORB]: true,
  [Ability.ROLLOUT]: true,
  [Ability.THRASH]: true,
  [Ability.SOLAR_BEAM]: true,
  [Ability.MAGMA_STORM]: true,
  [Ability.SLASHING_CLAW]: true,
  [Ability.ERUPTION]: true,
  [Ability.MIST_BALL]: true,
  [Ability.LUSTER_PURGE]: true,
  [Ability.MUD_BUBBLE]: true,
  [Ability.LINK_CABLE]: true,
  [Ability.MAGIC_BOUNCE]: true,
  [Ability.HIDDEN_POWER_A]: false,
  [Ability.HIDDEN_POWER_B]: false,
  [Ability.HIDDEN_POWER_C]: false,
  [Ability.HIDDEN_POWER_D]: false,
  [Ability.HIDDEN_POWER_E]: false,
  [Ability.HIDDEN_POWER_F]: false,
  [Ability.HIDDEN_POWER_G]: false,
  [Ability.HIDDEN_POWER_H]: false,
  [Ability.HIDDEN_POWER_I]: false,
  [Ability.HIDDEN_POWER_J]: false,
  [Ability.HIDDEN_POWER_K]: false,
  [Ability.HIDDEN_POWER_L]: false,
  [Ability.HIDDEN_POWER_M]: false,
  [Ability.HIDDEN_POWER_N]: false,
  [Ability.HIDDEN_POWER_O]: false,
  [Ability.HIDDEN_POWER_P]: false,
  [Ability.HIDDEN_POWER_Q]: false,
  [Ability.HIDDEN_POWER_R]: false,
  [Ability.HIDDEN_POWER_S]: false,
  [Ability.HIDDEN_POWER_T]: false,
  [Ability.HIDDEN_POWER_U]: false,
  [Ability.HIDDEN_POWER_V]: false,
  [Ability.HIDDEN_POWER_W]: false,
  [Ability.HIDDEN_POWER_X]: false,
  [Ability.HIDDEN_POWER_Y]: false,
  [Ability.HIDDEN_POWER_Z]: false,
  [Ability.HIDDEN_POWER_QM]: false,
  [Ability.HIDDEN_POWER_EM]: false,
  [Ability.POISON_JAB]: true,
  [Ability.SHELL_SMASH]: true
}
