export enum FreeOptions {
  BERRYBUNDLE = "BERRY_BUNDLE",
  UNOWNBUNDLE = "UNOWN_BUNDLE",
  SWEETSBUNDLE = "SWEETS_BUNDLE",
  DITTOBUNDLE = "DITTO_BUNDLE",
  TICKETBUNDLE = "TICKET_BUNDLE",
  HATCHBUNDLE = "HATCH_BUNDLE",
  REGIONBUNDLE = "REGION_BUNDLE",
  COOKINGBUNDLE = "COOKING_BUNDLE"
}

export enum PaidOptions {
  GEMSBUNDLE = "GEMS_BUNDLE",
  POTION = "POTION",
  DELUXE_BOX = "DELUXE_BOX",
  TOOLBUNDLE = "TOOL_BUNDLE",
  EXPBUNDLE = "EXP_BUNDLE",
  EVOLVEBUNDLE = "EVOLVE_BUNDLE",

  COMMONBUNDLE = "COMMON_BUNDLE",
  UNCOMMONBUNDLE = "UNCOMMON_BUNDLE",
  RAREBUNDLE = "RARE_BUNDLE",
  EPICBUNDLE = "EPIC_BUNDLE",
  ULTRABUNDLE = "ULTRA_BUNDLE",
  UNIQUEBUNDLE = "UNIQUE_BUNDLE",
  LEGENDARYBUNDLE = "LEGENDARY_BUNDLE"
}

export const GiftShopPrices: { [key in GiftShopOptions]: number } = {
  [FreeOptions.BERRYBUNDLE]: 0,
  [FreeOptions.UNOWNBUNDLE]: 0,
  [FreeOptions.SWEETSBUNDLE]: 0,
  [FreeOptions.DITTOBUNDLE]: 0,
  [FreeOptions.TICKETBUNDLE]: 0,
  [FreeOptions.HATCHBUNDLE]: 0,
  [FreeOptions.REGIONBUNDLE]: 0,
  [FreeOptions.COOKINGBUNDLE]: 0,

  [PaidOptions.EVOLVEBUNDLE]: 15,
  [PaidOptions.GEMSBUNDLE]: 5,
  [PaidOptions.POTION]: 5,
  [PaidOptions.DELUXE_BOX]: 15,
  [PaidOptions.TOOLBUNDLE]: 20,
  [PaidOptions.COMMONBUNDLE]: 15,
  [PaidOptions.UNCOMMONBUNDLE]: 6,
  [PaidOptions.RAREBUNDLE]: 9,
  [PaidOptions.EPICBUNDLE]: 12,
  [PaidOptions.ULTRABUNDLE]: 5,
  [PaidOptions.UNIQUEBUNDLE]: 15,
  [PaidOptions.LEGENDARYBUNDLE]: 50,
  [PaidOptions.EXPBUNDLE]: 20
}

export type GiftShopOptions = FreeOptions | PaidOptions
