export enum MaintenanceOrder {
  HEAP_SNAPSHOT = "HEAP_SNAPSHOT",
  FETCH_LEADERBOARDS = "FETCH_LEADERBOARDS",
  FETCH_META_REPORTS = "FETCH_META_REPORTS",
  REFRESH_SPRITE_GAP_DATA = "REFRESH_SPRITE_GAP_DATA",
  REFRESH_TWITCH_STREAMS = "REFRESH_TWITCH_STREAMS",
  REFRESH_TWITCH_BLACKLIST = "REFRESH_TWITCH_BLACKLIST"
}