export enum Passive {
    NONE = "NONE",
    TYROGUE = "TYROGUE",
    PROTEAN2 = "PROTEAN2",
    PROTEAN3 = "PROTEAN3",
    CASTFORM = "CASTFORM",
    PHIONE = "PHIONE",
    PRIMAL = "PRIMAL",
    WONDER_GUARD = "WONDER_GUARD",
}