export enum Passive {
    NONE = "NONE",
    TYROGUE = "TYROGUE",
    PROTEAN2 = "PROTEAN2",
    PROTEAN3 = "PROTEAN3",
    CASTFORM = "CASTFORM",
    PHIONE = "PHIONE",
    PRIMAL = "PRIMAL",
    WONDER_GUARD = "WONDER_GUARD",
    ELECTRIC_SURGE = "ELECTRIC_SURGE",
    GRASSY_SURGE = "GRASSY_SURGE",
    MISTY_SURGE = "MISTY_SURGE",
    PSYCHIC_SURGE = "PSYCHIC_SURGE",
    EEVEE = "EEVEE",
    TREE = "TREE",
    DITTO = "DITTO",
    EGG = "EGG",
    SYNCHRO = "SYNCHRO"
}