export enum Pkm {
    DITTO = 'ditto',
    BULBASAUR = 'bulbasaur',
    IVYSAUR = 'ivysaur',
    VENUSAUR = 'venusaur',
    CHARMANDER = 'charmander',
    CHARMELEON = 'charmeleon',
    CHARIZARD = 'charizard',
    SQUIRTLE = 'squirtle',
    WARTORTLE = 'wartortle',
    BLASTOISE = 'blastoise',
    GEODUDE = 'geodude',
    GRAVELER = 'graveler',
    GOLEM = 'golem',
    AZURILL = 'azurill',
    MARILL = 'marill',
    AZUMARILL = 'azumarill',
    ZUBAT = 'zubat',
    GOLBAT = 'golbat',
    CROBAT = 'crobat',
    MAREEP = 'mareep',
    FLAFFY = 'flaffy',
    AMPHAROS = 'ampharos',
    CLEFFA = 'cleffa',
    CLEFAIRY = 'clefairy',
    CLEFABLE = 'clefable',
    IGGLYBUFF = 'igglybuff',
    WIGGLYTUFF = 'wygglytuff',
    JIGGLYPUFF = 'jigglypuff',
    CATERPIE = 'caterpie',
    METAPOD = 'metapod',
    BUTTERFREE = 'butterfree',
    WEEDLE = 'weedle',
    KAKUNA = 'kakuna',
    BEEDRILL = 'beedrill',
    PIDGEY = 'pidgey',
    PIDGEOTTO = 'pidgeotto',
    PIDGEOT = 'pidgeot',
    HOPPIP = 'hoppip',
    SKIPLOOM = 'skiploom',
    JUMPLUFF = 'jumpluff',
    SEEDOT = 'seedot',
    NUZLEAF = 'nuzleaf',
    SHIFTRY = 'shiftry',
    STARLY = 'starly',
    STARAVIA = 'staravia',
    STARAPTOR = 'staraptor',
    CHIKORITA = 'chikorita',
    BAYLEEF = 'bayleef',
    MEGANIUM = 'meganium',
    CYNDAQUIL = 'cyndaquil',
    QUILAVA = 'quilava',
    TYPHLOSION = 'typlosion',
    TOTODILE = 'totodile',
    CROCONAW = 'croconaw',
    FERALIGATR = 'feraligatr',
    TREECKO = 'treecko',
    GROVYLE = 'grovyle',
    SCEPTILE = 'sceptile',
    TORCHIC = 'torchic',
    COMBUSKEN = 'combusken',
    BLAZIKEN = 'blaziken',
    MUDKIP = 'mudkip',
    MARSHTOMP = 'marshtomp',
    SWAMPERT = 'swampert',
    TURTWIG = 'turtwig',
    GROTLE = 'grotle',
    TORTERRA = 'torterra',
    CHIMCHAR = 'chimchar',
    MONFERNO = 'monferno',
    INFERNAPE = 'infernape',
    PIPLUP = 'piplup',
    PRINPLUP = 'prinplup',
    EMPOLEON = 'empoleon',
    NIDORANF = 'nidoranF',
    NIDORINA = 'nidorina',
    NIDOQUEEN = 'nidoqueen',
    NIDORANM = 'nidoranM',
    NIDORINO = 'nidorino',
    NIDOKING = 'nidoking',
    PICHU = 'pichu',
    PIKACHU = 'pikachu',
    RAICHU = 'raichu',
    MACHOP = 'machop',
    MACHOKE = 'machoke',
    MACHAMP = 'machamp',
    HORSEA = 'horsea',
    SEADRA = 'seadra',
    KINGDRA = 'kingdra',
    TRAPINCH = 'trapinch',
    VIBRAVA = 'vibrava',
    FLYGON = 'flygon',
    SPHEAL = 'spheal',
    SEALEO = 'sealeo',
    CHINCHOU = 'chinchou',
    WALREIN = 'walrein',
    ARON = 'aron',
    LAIRON = 'lairon',
    AGGRON = 'aggron',
    MAGNEMITE = 'magnemite',
    MAGNETON = 'magneton',
    MAGNEZONE = 'magnezone',
    RHYHORN = 'rhyhorn',
    RHYDON = 'rhydon',
    RHYPERIOR = 'rhyperior',
    TOGEPI = 'togepi',
    TOGETIC = 'togetic',
    TOGEKISS = 'togekiss',
    DUSKULL = 'duskull',
    DUSCLOPS = 'dusclops',
    DUSKNOIR = 'dusknoir',
    LOTAD = 'lotad',
    LOMBRE = 'lombre',
    LUDICOLO = 'ludicolo',
    SHINX = 'shinx',
    LUXIO = 'luxio',
    LUXRAY = 'luxray',
    POLIWAG = 'poliwag',
    POLIWHIRL = 'poliwhirl',
    POLITOED = 'politoed',
    ABRA = 'abra',
    KADABRA = 'kadabra',
    ALAKAZAM = 'alakazam',
    GASTLY = 'gastly',
    HAUNTER = 'haunter',
    GENGAR = 'gengar',
    DRATINI = 'dratini',
    DRAGONAIR = 'dragonair',
    DRAGONITE = 'dragonite',
    LARVITAR = 'larvitar',
    PUPITAR = 'pupitar',
    TYRANITAR = 'tyranitar',
    SLAKOTH = 'slakoth',
    VIGOROTH = 'vigoroth',
    SLAKING = 'slaking',
    RALTS = 'ralts',
    KIRLIA = 'kirlia',
    GARDEVOIR = 'gardevoir',
    BAGON = 'bagon',
    SHELGON = 'shelgon',
    SALAMENCE = 'salamence',
    BELDUM = 'beldum',
    METANG = 'metang',
    METAGROSS = 'metagross',
    GIBLE = 'gible',
    GABITE = 'gabite',
    GARCHOMP = 'garchomp',
    ELEKID = 'elekid',
    ELECTABUZZ = 'electabuzz',
    ELECTIVIRE = 'electivire',
    MAGBY = 'magby',
    MAGMAR = 'magmar',
    MAGMORTAR = 'magmortar',
    MUNCHLAX = 'munchlax',
    SNORLAX = 'snorlax',
    GROWLITHE = 'growlithe',
    ARCANINE = 'arcanine',
    ONIX = 'onix',
    STEELIX = 'steelix',
    MEGA_STEELIX = 'mega-steelix',
    SCYTHER = 'scyther',
    SCIZOR = 'scizor',
    MEGA_SCIZOR = 'mega-scizor',
    RIOLU = 'riolu',
    LUCARIO = 'lucario',
    MEGA_LUCARIO = 'mega-lucario',
    MAGIKARP = 'magikarp',
    RATTATA = 'rattata',
    RATICATE = 'raticate',
    SPEAROW = 'spearow',
    FEAROW = 'fearow',
    GYARADOS = 'gyarados',
    LUGIA = 'lugia',
    GIRATINA = 'giratina',
    ZAPDOS = 'zapdos',
    MOLTRES = 'moltres',
    ARTICUNO = 'articuno',
    DIALGA = 'dialga',
    PALKIA = 'palkia',
    SUICUNE = 'suicune',
    RAIKOU = 'raikou',
    ENTEI = 'entei',
    REGICE = 'regice',
    REGIROCK = 'regirock',
    REGISTEEL = 'registeel',
    KYOGRE = 'kyogre',
    GROUDON = 'groudon',
    RAYQUAZA = 'rayquaza',
    REGIGIGAS = 'regigigas',
    EEVEE = 'eevee',
    VAPOREON = 'vaporeon',
    JOLTEON = 'jolteon',
    FLAREON = 'flareon',
    ESPEON = 'espeon',
    UMBREON = 'umbreon',
    LEAFEON = 'leafeon',
    SYLVEON = 'sylveon',
    MEDITITE = 'meditite',
    MEDICHAM = 'medicham',
    MEGA_MEDICHAM = 'mega-medicham',
    NUMEL = 'numel',
    CAMERUPT = 'camerupt',
    MEGA_CAMERUPT = 'mega-camerupt',
    SANDSHREW = 'sandshrew',
    SANDSLASH = 'sandslash',
    DARKRAI = 'darkrai',
    LITWICK = 'litwick',
    LAMPENT = 'lampent',
    CHANDELURE = 'chandelure',
    SLOWPOKE = 'slowpoke',
    SLOWBRO = 'slowbro',
    SLOWKING = 'slowking',
    BELLSPROUT = 'bellsprout',
    WEEPINBELL = 'weepinbell',
    VICTREEBEL = 'victreebel',
    CARVANHA = 'carvanha',
    SWINUB = 'swinub',
    PILOSWINE = 'piloswine',
    MAMOSWINE = 'mamoswine',
    SNORUNT = 'snorunt',
    GLALIE = 'glalie',
    FROSLASS = 'froslass',
    SNOVER = 'snover',
    ABOMASNOW = 'abomasnow',
    MEGA_ABOMASNOW = 'mega-abomasnow',
    VANILLITE = 'vanillite',
    VANILLISH = 'vanillish',
    VANILLUXE = 'vanilluxe',
    GLACEON = 'glaceon',
    VOLCARONA = 'volcarona',
    LANDORUS = 'landorus',
    THUNDURUS = 'thundurus',
    TORNADUS = 'tornadus',
    KELDEO = 'keldeo',
    TERRAKION = 'terrakion',
    VIRIZION = 'virizion',
    COBALION = 'cobalion',
    MANAPHY = 'manaphy',
    ROTOM = 'rotom',
    SPIRITOMB = 'spiritomb',
    ABSOL = 'absol',
    LAPRAS = 'lapras',
    LATIAS = 'latias',
    LATIOS = 'latios',
    MESPRIT = 'mesprit',
    AZELF = 'azelf',
    UXIE = 'uxie',
    MEWTWO = 'mewtwo',
    KYUREM = 'kyurem',
    RESHIRAM = 'reshiram',
    ZEKROM = 'zekrom',
    CELEBI = 'celebi',
    VICTINI = 'victini',
    JIRACHI = 'jirachi',
    ARCEUS = 'arceus',
    DEOXYS = 'deoxys',
    SHAYMIN = 'shaymin',
    CRESSELIA = 'cresselia',
    HEATRAN = 'heatran',
    HO_OH = 'ho-Oh',
    AERODACTYL = 'aerodactyl',
    PRIMAL_KYOGRE = 'primal-Kyogre',
    PRIMAL_GROUDON = 'primal-Groudon',
    MEOWTH = 'meowth',
    PERSIAN = 'persian',
    DEINO = 'deino',
    ZWEILOUS = 'zweilous',
    HYDREIGON = 'hydreigon',
    SANDILE = 'sandile',
    KROKOROK = 'krokorok',
    KROOKODILE = 'krookodile',
    SOLOSIS = 'solosis',
    DUOSION = 'duosion',
    REUNICLUS = 'reuniclus',
    MEGA_RAYQUAZA = 'mega-Rayquaza',
    SWABLU = 'swablu',
    ODDISH = 'oddish',
    GLOOM = 'gloom',
    VILEPLUME = 'vileplume',
    BELLOSSOM = 'bellossom',
    AMAURA = 'amaura',
    AURORUS = 'aurorus',
    ANORITH = 'anorith',
    ARMALDO = 'armaldo',
    ARCHEN = 'archen',
    ARCHEOPS = 'archeops',
    SHIELDON = 'shieldon',
    BASTIODON = 'bastiodon',
    TIRTOUGA = 'tirtouga',
    CARRACOSTA = 'carracosta',
    LILEEP = 'lileep',
    CRADILY = 'cradily',
    CRANIDOS = 'cranidos',
    RAMPARDOS = 'rampardos',
    KABUTO = 'kabuto',
    KABUTOPS = 'kabutops',
    OMANYTE = 'omanyte',
    OMASTAR = 'omastar',
    TYRUNT = 'tyrunt',
    TYRANTRUM = 'tyrantrum',
    BUDEW = 'budew',
    ROSELIA = 'roselia',
    ROSERADE = 'roserade',
    BUNEARY = 'buneary',
    LOPUNNY = 'lopunny',
    MEGA_LOPUNNY = 'mega-lopunny',
    AXEW = 'axew',
    FRAXURE = 'fraxure',
    HAXORUS = 'haxorus',
    VENIPEDE = 'venipede',
    WHIRLIPEDE = 'whirlipede',
    SCOLIPEDE = 'scolipede',
    PORYGON = 'porygon',
    PORYGON_2 = 'porygon2',
    PORYGON_Z = 'porygon-z',
    KLINK = 'klink',
    KLANG = 'klang',
    KLINKLANG = 'klinklang',
    ELECTRIKE = 'electrike',
    MANECTRIC = 'manectric',
    MEGA_MANECTRIC = 'mega-manectric',
    SHUPPET = 'shuppet',
    BANETTE = 'banette',
    MEGA_BANETTE = 'mega-banette',
    HONEDGE = 'honedge',
    DOUBLADE = 'doublade',
    AEGISLASH = 'aegislash',
    CUBONE = 'cubone',
    MAROWAK = 'marowak',
    ALOLAN_MAROWAK = 'alolan-marowak',
    FLETCHLING = 'fletchling',
    FLETCHINDER = 'fletchinder',
    TALONFLAME = 'talonflame',
    WHISMUR = 'whismur',
    LOUDRED = 'loudred',
    EXPLOUD = 'exploud',
    TYMPOLE = 'tympole',
    PALPITOAD = 'palpitoad',
    SEISMITOAD = 'seismitoad',
    SEWADDLE = 'sewaddle',
    SWADLOON = 'swadloon',
    LEAVANNY = 'leavanny',
    PIKIPEK = 'pikipek',
    TRUMBEAK = 'trumbeak',
    TOUCANNON = 'toucannon',
    FLABEBE = 'flabebe',
    FLOETTE = 'floette',
    FLORGES = 'florges',
    JANGMO_O = 'jangmo-o',
    HAKAMO_O = 'hakamo-o',
    KOMMO_O = 'kommo-o',
    MELOETTA = 'meloetta',
    ALTARIA = 'altaria',
    MEGA_ALTARIA = 'mega-altaria',
    LILLIPUP = 'lillipup',
    HERDIER = 'herdier',
    STOUTLAND = 'stoutland',
    HITMONCHAN = 'hitmonchan',
    SKUNTANK = 'skuntank',
    PRIMEAPE = 'primeape',
    URSARING = 'ursaring',
    BIBAREL = 'bibarel',
    SENTRET = 'sentret',
    FURRET = 'furret',
    LUNATONE = 'lunatone',
    HONCHKROW = 'honchkrow',
    GLAMEOW = 'glameow',
    PURUGLY = 'purugly',
    TOXICROAK = 'toxicroak',
    SKARMORY = 'skarmory',
    LICKILICKY = 'lickilicky',
    LICKITUNG = 'lickitung',
    TANGELA = 'tangela',
    TANGROWTH = 'tangrowth',
    MISDREAVUS = 'misdreavus',
    MISMAGIUS = 'mismagius',
    SOLROCK = 'solrock',
    SKORUPI = 'skorupi',
    CLAYDOL = 'claydol',
    BALTOY = 'baltoy',
    GLISCOR = 'gliscor',
    MUK = 'muk',
    NOSEPASS = 'nosepass',
    PROBOPASS = 'probopass',
    SURSKIT = 'surskit',
    MASQUERAIN = 'masquerain',
    VOLBEAT = 'volbeat',
    ILLUMISE = 'illumise',
    DIGLETT = 'diglett',
    DUGTRIO = 'dugtrio',
    SEVIPER = 'seviper',
    WEEZING = 'weezing',
    KOFFING = 'koffing',
    CACTURNE = 'cacturne',
    CACNEA = 'cacnea',
    DRIFBLIM = 'drifblim',
    DRIFLOON = 'drifloon',
    KINGLER = 'kingler',
    KRABBY = 'krabby',
    EXEGGCUTE = 'exeggcute',
    HOOTHOOT = 'hoothoot',
    NOCTOWL = 'noctowl',
    DODUO = 'doduo',
    DODRIO = 'dodrio',
    TAUROS = 'tauros',
    BURMY = 'burmy',
    WORMADAN = 'wormadan',
    SPINARAK = 'spinarak',
    ARIADOS = 'ariados',
    WURMPLE = 'wurmple',
    BRONZONG = 'bronzong',
    BRONZOR = 'bronzor',
    DROWZEE = 'drowzee',
    HYPNO = 'hypno',
    SMOOCHUM = 'smoochum',
    PLUSLE = 'plusle',
    MINUN = 'minun',
    PHANPY = 'phanpy',
    GIRAFARIG = 'girafarig',
    YANMA = 'yanma',
    YANMEGA = 'yanmega',
    POOCHYENA = 'poochyena',
    MIGHTYENA = 'mightyena',
    SHROOMISH = 'shroomish',
    CARNIVINE = 'carnivine',
    MAWILE = 'mawile',
    DUNSPARCE = 'dunsparce',
    SMEARGLE = 'smeargle',
    CHERUBI = 'cherubi',
    CHERIM = 'cherim',
    ZIGZAGOON = 'zigzagoon',
    PACHIRISU = 'pachirisu',
    STANTLER = 'stantler',
    PINSIR = 'pinsir',
    BRELOOM = 'breloom',
    LINOONE = 'linoone',
    KRICKEROT = 'krickerot',
    TROPIUS = 'tropius',
    MEW = 'mew',
    SHELLDER = 'shellder',
    CORSOLA = 'corsola',
    SHELLOS = 'shellos',
    GASTRODON = 'gastrodon',
    WAILMER = 'wailmer',
    WAILORD = 'wailord',
    CLAMPERL = 'clamperl',
    FINNEON = 'finneon',
    TENTACOOL = 'tentacool',
    TENTACRUEL = 'tentacruel',
    REMORAID = 'remoraid',
    SEEL = 'seel',
    DEWGONG = 'dewgong',
    PELIPPER = 'pelipper',
    STARYU = 'staryu',
    STARMIE = 'starmie',
    SPOINK = 'spoink',
    GRUMPIG = 'grumpig',
    VOLTORB = 'voltorb',
    ELECTRODE = 'electrode',
    MURKROW = 'murkrow',
    SKITTY = 'skitty',
    DELCATTY = 'delcatty',
    TAILOW = 'tailow',
    SWELLOW = 'swellow',
    WINGULL = 'wingull',
    DONPHAN = 'donphan',
    FLOATZEL = 'floatzel',
    PONYTA = 'ponyta',
    RAPIDASH = 'rapidash',
    SLUGMA = 'slugma',
    MAGCARGO = 'magcargo',
    HIPPOWDON = 'hippowdon',
    HIPPOPOTAS = 'hippopotas',
    VULPIX = 'vulpix',
    NINETALES = 'ninetales',
    FORETRESS = 'foretress',
    CHINGLING = 'chingling',
    MOTHIM = 'mothim',
    NINCADA = 'nincada',
    NINJASK = 'ninjask',
    SHEDNINJA = 'shedninja',
    UNOWN = 'unown',
    OCTIRELLY = 'octirelly',
    QWILFISH = 'qwilfish',
    CHANSEY = 'chansey',
    BLISSEY = 'blissey',
    WYNAUT = 'wynaut',
    WOOBUFFET = 'woobuffet',
    SPINDA = 'spinda',
    MILTANK = 'miltank',
    VESPIQUEEN = 'vespiqueen',
    HOUNDOUR = 'houndour',
    HOUNDOOM = 'houndoom',
    SNUBULL = 'snubull',
    GRANBULL = 'granbull',
    FARFETCH = 'farfetch',
    KRICKETUNE = 'kricketune',
    GRIMER = 'grimer',
    PSYDUCK = 'psyduck',
    WOOPER = 'wooper',
    BARBOACH = 'barboach',
    WHISCASH = 'whiscash',
    SNEASEL = 'sneasel',
    SABLEYE = 'sableye',
    SUDOWOODO = 'sudowoodo',
    EKANS = 'ekans',
    ARBOK = 'arbok',
    CASTFORM = 'castform',
    CASTFORM_SUN = 'castform-sun',
    CASTFORM_RAIN = 'castform-rain',
    CASTFORM_HAIL = 'castform-hail'
}

export const PokemonIndex: {[key in Pkm] : string} = {
   [Pkm.DITTO]: "0132",
   [Pkm.BULBASAUR]: "0001",
   [Pkm.IVYSAUR]: "0002",
   [Pkm.VENUSAUR]: "0003",
   [Pkm.CHARMANDER]: "0004",
   [Pkm.CHARMELEON]: "0005",
   [Pkm.CHARIZARD]: "0006",
   [Pkm.SQUIRTLE]: "0007",
   [Pkm.WARTORTLE]: "0008",
   [Pkm.BLASTOISE]: "0009",
   [Pkm.GEODUDE]: "0074",
   [Pkm.GRAVELER]: "0075",
   [Pkm.GOLEM]: "0076",
   [Pkm.AZURILL]: "0298",
   [Pkm.MARILL]: "0183",
   [Pkm.AZUMARILL]: "0184",
   [Pkm.ZUBAT]: "0041",
   [Pkm.GOLBAT]: "0042",
   [Pkm.CROBAT]: "0169",
   [Pkm.MAREEP]: "0179",
   [Pkm.FLAFFY]: "0180",
   [Pkm.AMPHAROS]: "0181",
   [Pkm.CLEFFA]: "0173",
   [Pkm.CLEFAIRY]: "0035",
   [Pkm.CLEFABLE]: "0036",
   [Pkm.IGGLYBUFF]: "0174",
   [Pkm.WIGGLYTUFF]: "0040",
   [Pkm.JIGGLYPUFF]: "0039",
   [Pkm.CATERPIE]: "0010",
   [Pkm.METAPOD]: "0011",
   [Pkm.BUTTERFREE]: "0012",
   [Pkm.WEEDLE]: "0013",
   [Pkm.KAKUNA]: "0014",
   [Pkm.BEEDRILL]: "0015",
   [Pkm.PIDGEY]: "0016",
   [Pkm.PIDGEOTTO]: "0017",
   [Pkm.PIDGEOT]: "0018",
   [Pkm.HOPPIP]: "0187",
   [Pkm.SKIPLOOM]: "0188",
   [Pkm.JUMPLUFF]: "0189",
   [Pkm.SEEDOT]: "0273",
   [Pkm.NUZLEAF]: "0274",
   [Pkm.SHIFTRY]: "0275",
   [Pkm.STARLY]: "0396",
   [Pkm.STARAVIA]: "0397",
   [Pkm.STARAPTOR]: "0398",
   [Pkm.CHIKORITA]: "0152",
   [Pkm.BAYLEEF]: "0153",
   [Pkm.MEGANIUM]: "0154",
   [Pkm.CYNDAQUIL]: "0155",
   [Pkm.QUILAVA]: "0156",
   [Pkm.TYPHLOSION]: "0157",
   [Pkm.TOTODILE]: "0158",
   [Pkm.CROCONAW]: "0159",
   [Pkm.FERALIGATR]: "0160",
   [Pkm.TREECKO]: "0252",
   [Pkm.GROVYLE]: "0253",
   [Pkm.SCEPTILE]: "0254",
   [Pkm.TORCHIC]: "0255",
   [Pkm.COMBUSKEN]: "0256",
   [Pkm.BLAZIKEN]: "0257",
   [Pkm.MUDKIP]: "0258",
   [Pkm.MARSHTOMP]: "0259",
   [Pkm.SWAMPERT]: "0260",
   [Pkm.TURTWIG]: "0387",
   [Pkm.GROTLE]: "0388",
   [Pkm.TORTERRA]: "0389",
   [Pkm.CHIMCHAR]: "0390",
   [Pkm.MONFERNO]: "0391",
   [Pkm.INFERNAPE]: "0392",
   [Pkm.PIPLUP]: "0393",
   [Pkm.PRINPLUP]: "0394",
   [Pkm.EMPOLEON]: "0395",
   [Pkm.NIDORANF]: "0029",
   [Pkm.NIDORINA]: "0030",
   [Pkm.NIDOQUEEN]: "0031",
   [Pkm.NIDORANM]: "0032",
   [Pkm.NIDORINO]: "0033",
   [Pkm.NIDOKING]: "0034",
   [Pkm.PICHU]: "0172",
   [Pkm.PIKACHU]: "0025",
   [Pkm.RAICHU]: "0026",
   [Pkm.MACHOP]: "0066",
   [Pkm.MACHOKE]: "0067",
   [Pkm.MACHAMP]: "0068",
   [Pkm.HORSEA]: "0116",
   [Pkm.SEADRA]: "0117",
   [Pkm.KINGDRA]: "0230",
   [Pkm.TRAPINCH]: "0328",
   [Pkm.VIBRAVA]: "0329",
   [Pkm.FLYGON]: "0330",
   [Pkm.SPHEAL]: "0363",
   [Pkm.SEALEO]: "0364",
   [Pkm.CHINCHOU]: "0129",
   [Pkm.WALREIN]: "0365",
   [Pkm.ARON]: "0304",
   [Pkm.LAIRON]: "0305",
   [Pkm.AGGRON]: "0306",
   [Pkm.MAGNEMITE]: "0081",
   [Pkm.MAGNETON]: "0082",
   [Pkm.MAGNEZONE]: "0462",
   [Pkm.RHYHORN]: "0111",
   [Pkm.RHYDON]: "0112",
   [Pkm.RHYPERIOR]: "0464",
   [Pkm.TOGEPI]: "0175",
   [Pkm.TOGETIC]: "0176",
   [Pkm.TOGEKISS]: "0468",
   [Pkm.DUSKULL]: "0355",
   [Pkm.DUSCLOPS]: "0356",
   [Pkm.DUSKNOIR]: "0477",
   [Pkm.LOTAD]: "0270",
   [Pkm.LOMBRE]: "0271",
   [Pkm.LUDICOLO]: "0272",
   [Pkm.SHINX]: "0403",
   [Pkm.LUXIO]: "0404",
   [Pkm.LUXRAY]: "0405",
   [Pkm.POLIWAG]: "0060",
   [Pkm.POLIWHIRL]: "0061",
   [Pkm.POLITOED]: "0186",
   [Pkm.ABRA]: "0063",
   [Pkm.KADABRA]: "0064",
   [Pkm.ALAKAZAM]: "0065",
   [Pkm.GASTLY]: "0092",
   [Pkm.HAUNTER]: "0093",
   [Pkm.GENGAR]: "0094",
   [Pkm.DRATINI]: "0147",
   [Pkm.DRAGONAIR]: "0148",
   [Pkm.DRAGONITE]: "0149",
   [Pkm.LARVITAR]: "0246",
   [Pkm.PUPITAR]: "0247",
   [Pkm.TYRANITAR]: "0248",
   [Pkm.SLAKOTH]: "0287",
   [Pkm.VIGOROTH]: "0288",
   [Pkm.SLAKING]: "0289",
   [Pkm.RALTS]: "0280",
   [Pkm.KIRLIA]: "0281",
   [Pkm.GARDEVOIR]: "0282",
   [Pkm.BAGON]: "0371",
   [Pkm.SHELGON]: "0372",
   [Pkm.SALAMENCE]: "0373",
   [Pkm.BELDUM]: "0374",
   [Pkm.METANG]: "0375",
   [Pkm.METAGROSS]: "0376",
   [Pkm.GIBLE]: "0443",
   [Pkm.GABITE]: "0444",
   [Pkm.GARCHOMP]: "0445",
   [Pkm.ELEKID]: "0239",
   [Pkm.ELECTABUZZ]: "0125",
   [Pkm.ELECTIVIRE]: "0466",
   [Pkm.MAGBY]: "0240",
   [Pkm.MAGMAR]: "0126",
   [Pkm.MAGMORTAR]: "0467",
   [Pkm.MUNCHLAX]: "0446",
   [Pkm.SNORLAX]: "0143",
   [Pkm.GROWLITHE]: "0058",
   [Pkm.ARCANINE]: "0059",
   [Pkm.ONIX]: "0095",
   [Pkm.STEELIX]: "0208",
   [Pkm.MEGA_STEELIX]: "0208-0001",
   [Pkm.SCYTHER]: "0123",
   [Pkm.SCIZOR]: "0212",
   [Pkm.MEGA_SCIZOR]: "0212-0001",
   [Pkm.RIOLU]: "0447",
   [Pkm.LUCARIO]: "0448",
   [Pkm.MEGA_LUCARIO]: "0448-0001",
   [Pkm.MAGIKARP]: "0129",
   [Pkm.RATTATA]: "0019",
   [Pkm.RATICATE]: "0020",
   [Pkm.SPEAROW]: "0021",
   [Pkm.FEAROW]: "0022",
   [Pkm.GYARADOS]: "0130",
   [Pkm.LUGIA]: "0249",
   [Pkm.GIRATINA]: "0487",
   [Pkm.ZAPDOS]: "0145",
   [Pkm.MOLTRES]: "0146",
   [Pkm.ARTICUNO]: "0144",
   [Pkm.DIALGA]: "0483",
   [Pkm.PALKIA]: "0484",
   [Pkm.SUICUNE]: "0245",
   [Pkm.RAIKOU]: "0243",
   [Pkm.ENTEI]: "0244",
   [Pkm.REGICE]: "0378",
   [Pkm.REGIROCK]: "0377",
   [Pkm.REGISTEEL]: "0379",
   [Pkm.KYOGRE]: "0382",
   [Pkm.GROUDON]: "0383",
   [Pkm.RAYQUAZA]: "0384",
   [Pkm.REGIGIGAS]: "0486",
   [Pkm.EEVEE]: "0133",
   [Pkm.VAPOREON]: "0134",
   [Pkm.JOLTEON]: "0135",
   [Pkm.FLAREON]: "0136",
   [Pkm.ESPEON]: "0196",
   [Pkm.UMBREON]: "0197",
   [Pkm.LEAFEON]: "0470",
   [Pkm.SYLVEON]: "0700",
   [Pkm.MEDITITE]: "0307",
   [Pkm.MEDICHAM]: "0308",
   [Pkm.MEGA_MEDICHAM]: "0308-0001",
   [Pkm.NUMEL]: "0322",
   [Pkm.CAMERUPT]: "0323",
   [Pkm.MEGA_CAMERUPT]: "0323-0001",
   [Pkm.SANDSHREW]: "0027",
   [Pkm.SANDSLASH]: "0129",
   [Pkm.DARKRAI]: "0491",
   [Pkm.LITWICK]: "0607",
   [Pkm.LAMPENT]: "0608",
   [Pkm.CHANDELURE]: "0609",
   [Pkm.SLOWPOKE]: "0079",
   [Pkm.SLOWBRO]: "0080",
   [Pkm.SLOWKING]: "0199",
   [Pkm.BELLSPROUT]: "0069",
   [Pkm.WEEPINBELL]: "0070",
   [Pkm.VICTREEBEL]: "0071",
   [Pkm.CARVANHA]: "0318",
   [Pkm.SWINUB]: "0220",
   [Pkm.PILOSWINE]: "0221",
   [Pkm.MAMOSWINE]: "0473",
   [Pkm.SNORUNT]: "0361",
   [Pkm.GLALIE]: "0362",
   [Pkm.FROSLASS]: "0478",
   [Pkm.SNOVER]: "0459",
   [Pkm.ABOMASNOW]: "0460",
   [Pkm.MEGA_ABOMASNOW]: "0460-0001",
   [Pkm.VANILLITE]: "0582",
   [Pkm.VANILLISH]: "0583",
   [Pkm.VANILLUXE]: "0584",
   [Pkm.GLACEON]: "0471",
   [Pkm.VOLCARONA]: "0637",
   [Pkm.LANDORUS]: "0645",
   [Pkm.THUNDURUS]: "0642",
   [Pkm.TORNADUS]: "0641",
   [Pkm.KELDEO]: "0647",
   [Pkm.TERRAKION]: "0639",
   [Pkm.VIRIZION]: "0640",
   [Pkm.COBALION]: "0638",
   [Pkm.MANAPHY]: "0490",
   [Pkm.ROTOM]: "0479",
   [Pkm.SPIRITOMB]: "0442",
   [Pkm.ABSOL]: "0359",
   [Pkm.LAPRAS]: "0131",
   [Pkm.LATIAS]: "0380",
   [Pkm.LATIOS]: "0381",
   [Pkm.MESPRIT]: "0481",
   [Pkm.AZELF]: "0482",
   [Pkm.UXIE]: "0480",
   [Pkm.MEWTWO]: "0150",
   [Pkm.KYUREM]: "0646",
   [Pkm.RESHIRAM]: "0643",
   [Pkm.ZEKROM]: "0644",
   [Pkm.CELEBI]: "0251",
   [Pkm.VICTINI]: "0494",
   [Pkm.JIRACHI]: "0385",
   [Pkm.ARCEUS]: "0493",
   [Pkm.DEOXYS]: "0386",
   [Pkm.SHAYMIN]: "0492",
   [Pkm.CRESSELIA]: "0488",
   [Pkm.HEATRAN]: "0485",
   [Pkm.HO_OH]: "0250",
   [Pkm.AERODACTYL]: "0142",
   [Pkm.PRIMAL_KYOGRE]: "0382-0001",
   [Pkm.PRIMAL_GROUDON]: "0383-0001",
   [Pkm.MEOWTH]: "0052",
   [Pkm.PERSIAN]: "0053",
   [Pkm.DEINO]: "0633",
   [Pkm.ZWEILOUS]: "0634",
   [Pkm.HYDREIGON]: "0635",
   [Pkm.SANDILE]: "0551",
   [Pkm.KROKOROK]: "0552",
   [Pkm.KROOKODILE]: "0553",
   [Pkm.SOLOSIS]: "0577",
   [Pkm.DUOSION]: "0578",
   [Pkm.REUNICLUS]: "0579",
   [Pkm.MEGA_RAYQUAZA]: "0384-0001",
   [Pkm.SWABLU]: "0333",
   [Pkm.ODDISH]: "0043",
   [Pkm.GLOOM]: "0044",
   [Pkm.VILEPLUME]: "0045",
   [Pkm.BELLOSSOM]: "0182",
   [Pkm.AMAURA]: "0698",
   [Pkm.AURORUS]: "0699",
   [Pkm.ANORITH]: "0347",
   [Pkm.ARMALDO]: "0348",
   [Pkm.ARCHEN]: "0566",
   [Pkm.ARCHEOPS]: "0567",
   [Pkm.SHIELDON]: "0410",
   [Pkm.BASTIODON]: "0411",
   [Pkm.TIRTOUGA]: "0564",
   [Pkm.CARRACOSTA]: "0565",
   [Pkm.LILEEP]: "0345",
   [Pkm.CRADILY]: "0346",
   [Pkm.CRANIDOS]: "0408",
   [Pkm.RAMPARDOS]: "0409",
   [Pkm.KABUTO]: "0140",
   [Pkm.KABUTOPS]: "0141",
   [Pkm.OMANYTE]: "0138",
   [Pkm.OMASTAR]: "0139",
   [Pkm.TYRUNT]: "0696",
   [Pkm.TYRANTRUM]: "0697",
   [Pkm.BUDEW]: "0406",
   [Pkm.ROSELIA]: "0315",
   [Pkm.ROSERADE]: "0407",
   [Pkm.BUNEARY]: "0427",
   [Pkm.LOPUNNY]: "0428",
   [Pkm.MEGA_LOPUNNY]: "0428-0001",
   [Pkm.AXEW]: "0610",
   [Pkm.FRAXURE]: "0611",
   [Pkm.HAXORUS]: "0612",
   [Pkm.VENIPEDE]: "0543",
   [Pkm.WHIRLIPEDE]: "0544",
   [Pkm.SCOLIPEDE]: "0545",
   [Pkm.PORYGON]: "0137",
   [Pkm.PORYGON_2]: "0233",
   [Pkm.PORYGON_Z]: "0474",
   [Pkm.KLINK]: "0599",
   [Pkm.KLANG]: "0600",
   [Pkm.KLINKLANG]: "0601",
   [Pkm.ELECTRIKE]: "0309",
   [Pkm.MANECTRIC]: "0310",
   [Pkm.MEGA_MANECTRIC]: "0310-0001",
   [Pkm.SHUPPET]: "0353",
   [Pkm.BANETTE]: "0354",
   [Pkm.MEGA_BANETTE]: "0354-0001",
   [Pkm.HONEDGE]: "0679",
   [Pkm.DOUBLADE]: "0680",
   [Pkm.AEGISLASH]: "0681",
   [Pkm.CUBONE]: "0104",
   [Pkm.MAROWAK]: "0105",
   [Pkm.ALOLAN_MAROWAK]: "0105/0001",
   [Pkm.FLETCHLING]: "0661",
   [Pkm.FLETCHINDER]: "0662",
   [Pkm.TALONFLAME]: "0663",
   [Pkm.WHISMUR]: "0293",
   [Pkm.LOUDRED]: "0294",
   [Pkm.EXPLOUD]: "0295",
   [Pkm.TYMPOLE]: "0535",
   [Pkm.PALPITOAD]: "0536",
   [Pkm.SEISMITOAD]: "0537",
   [Pkm.SEWADDLE]: "0540",
   [Pkm.SWADLOON]: "0541",
   [Pkm.LEAVANNY]: "0542",
   [Pkm.PIKIPEK]: "0731",
   [Pkm.TRUMBEAK]: "0732",
   [Pkm.TOUCANNON]: "0733",
   [Pkm.FLABEBE]: "0669",
   [Pkm.FLOETTE]: "0670",
   [Pkm.FLORGES]: "0671",
   [Pkm.JANGMO_O]: "0782",
   [Pkm.HAKAMO_O]: "0783",
   [Pkm.KOMMO_O]: "0784",
   [Pkm.MELOETTA]: "0648",
   [Pkm.ALTARIA]: "0334",
   [Pkm.MEGA_ALTARIA]: "0334-0001",
   [Pkm.LILLIPUP]: "0506",
   [Pkm.HERDIER]: "0507",
   [Pkm.STOUTLAND]: "0508",
   [Pkm.HITMONCHAN]: "0129",
   [Pkm.SKUNTANK]: "0129",
   [Pkm.PRIMEAPE]: "0129",
   [Pkm.URSARING]: "0129",
   [Pkm.BIBAREL]: "0129",
   [Pkm.SENTRET]: "0129",
   [Pkm.FURRET]: "0129",
   [Pkm.LUNATONE]: "0129",
   [Pkm.HONCHKROW]: "0129",
   [Pkm.GLAMEOW]: "0129",
   [Pkm.PURUGLY]: "0129",
   [Pkm.TOXICROAK]: "0129",
   [Pkm.SKARMORY]: "0129",
   [Pkm.LICKILICKY]: "0129",
   [Pkm.LICKITUNG]: "0129",
   [Pkm.TANGELA]: "0129",
   [Pkm.TANGROWTH]: "0129",
   [Pkm.MISDREAVUS]: "0129",
   [Pkm.MISMAGIUS]: "0129",
   [Pkm.SOLROCK]: "0129",
   [Pkm.SKORUPI]: "0129",
   [Pkm.CLAYDOL]: "0129",
   [Pkm.BALTOY]: "0129",
   [Pkm.GLISCOR]: "0129",
   [Pkm.MUK]: "0129",
   [Pkm.NOSEPASS]: "0129",
   [Pkm.PROBOPASS]: "0129",
   [Pkm.SURSKIT]: "0129",
   [Pkm.MASQUERAIN]: "0129",
   [Pkm.VOLBEAT]: "0129",
   [Pkm.ILLUMISE]: "0129",
   [Pkm.DIGLETT]: "0129",
   [Pkm.DUGTRIO]: "0129",
   [Pkm.SEVIPER]: "0129",
   [Pkm.WEEZING]: "0129",
   [Pkm.KOFFING]: "0129",
   [Pkm.CACTURNE]: "0129",
   [Pkm.CACNEA]: "0129",
   [Pkm.DRIFBLIM]: "0129",
   [Pkm.DRIFLOON]: "0129",
   [Pkm.KINGLER]: "0129",
   [Pkm.KRABBY]: "0129",
   [Pkm.EXEGGCUTE]: "0129",
   [Pkm.HOOTHOOT]: "0129",
   [Pkm.NOCTOWL]: "0129",
   [Pkm.DODUO]: "0129",
   [Pkm.DODRIO]: "0129",
   [Pkm.TAUROS]: "0129",
   [Pkm.BURMY]: "0129",
   [Pkm.WORMADAN]: "0129",
   [Pkm.SPINARAK]: "0129",
   [Pkm.ARIADOS]: "0129",
   [Pkm.WURMPLE]: "0129",
   [Pkm.BRONZONG]: "0129",
   [Pkm.BRONZOR]: "0129",
   [Pkm.DROWZEE]: "0129",
   [Pkm.HYPNO]: "0129",
   [Pkm.SMOOCHUM]: "0129",
   [Pkm.PLUSLE]: "0129",
   [Pkm.MINUN]: "0129",
   [Pkm.PHANPY]: "0129",
   [Pkm.GIRAFARIG]: "0129",
   [Pkm.YANMA]: "0129",
   [Pkm.YANMEGA]: "0129",
   [Pkm.POOCHYENA]: "0129",
   [Pkm.MIGHTYENA]: "0129",
   [Pkm.SHROOMISH]: "0129",
   [Pkm.CARNIVINE]: "0129",
   [Pkm.MAWILE]: "0129",
   [Pkm.DUNSPARCE]: "0129",
   [Pkm.SMEARGLE]: "0129",
   [Pkm.CHERUBI]: "0129",
   [Pkm.CHERIM]: "0129",
   [Pkm.ZIGZAGOON]: "0129",
   [Pkm.PACHIRISU]: "0129",
   [Pkm.STANTLER]: "0129",
   [Pkm.PINSIR]: "0129",
   [Pkm.BRELOOM]: "0129",
   [Pkm.LINOONE]: "0129",
   [Pkm.KRICKEROT]: "0129",
   [Pkm.TROPIUS]: "0129",
   [Pkm.MEW]: "0129",
   [Pkm.SHELLDER]: "0129",
   [Pkm.CORSOLA]: "0129",
   [Pkm.SHELLOS]: "0129",
   [Pkm.GASTRODON]: "0129",
   [Pkm.WAILMER]: "0129",
   [Pkm.WAILORD]: "0129",
   [Pkm.CLAMPERL]: "0129",
   [Pkm.FINNEON]: "0129",
   [Pkm.TENTACOOL]: "0129",
   [Pkm.TENTACRUEL]: "0129",
   [Pkm.REMORAID]: "0129",
   [Pkm.SEEL]: "0129",
   [Pkm.DEWGONG]: "0129",
   [Pkm.PELIPPER]: "0129",
   [Pkm.STARYU]: "0129",
   [Pkm.STARMIE]: "0129",
   [Pkm.SPOINK]: "0129",
   [Pkm.GRUMPIG]: "0129",
   [Pkm.VOLTORB]: "0129",
   [Pkm.ELECTRODE]: "0129",
   [Pkm.MURKROW]: "0129",
   [Pkm.SKITTY]: "0129",
   [Pkm.DELCATTY]: "0129",
   [Pkm.TAILOW]: "0129",
   [Pkm.SWELLOW]: "0129",
   [Pkm.WINGULL]: "0129",
   [Pkm.DONPHAN]: "0129",
   [Pkm.FLOATZEL]: "0129",
   [Pkm.PONYTA]: "0129",
   [Pkm.RAPIDASH]: "0129",
   [Pkm.SLUGMA]: "0129",
   [Pkm.MAGCARGO]: "0129",
   [Pkm.HIPPOWDON]: "0129",
   [Pkm.HIPPOPOTAS]: "0129",
   [Pkm.VULPIX]: "0129",
   [Pkm.NINETALES]: "0129",
   [Pkm.FORETRESS]: "0129",
   [Pkm.CHINGLING]: "0129",
   [Pkm.MOTHIM]: "0129",
   [Pkm.NINCADA]: "0129",
   [Pkm.NINJASK]: "0129",
   [Pkm.SHEDNINJA]: "0129",
   [Pkm.UNOWN]: "0129",
   [Pkm.OCTIRELLY]: "0129",
   [Pkm.QWILFISH]: "0129",
   [Pkm.CHANSEY]: "0129",
   [Pkm.BLISSEY]: "0129",
   [Pkm.WYNAUT]: "0129",
   [Pkm.WOOBUFFET]: "0129",
   [Pkm.SPINDA]: "0129",
   [Pkm.MILTANK]: "0129",
   [Pkm.VESPIQUEEN]: "0129",
   [Pkm.HOUNDOUR]: "0228",
   [Pkm.HOUNDOOM]: "0129",
   [Pkm.SNUBULL]: "0129",
   [Pkm.GRANBULL]: "0129",
   [Pkm.FARFETCH]: "0129",
   [Pkm.KRICKETUNE]: "0129",
   [Pkm.GRIMER]: "0129",
   [Pkm.PSYDUCK]: "0129",
   [Pkm.WOOPER]: "0129",
   [Pkm.BARBOACH]: "0129",
   [Pkm.WHISCASH]: "0129",
   [Pkm.SNEASEL]: "0129",
   [Pkm.SABLEYE]: "0129",
   [Pkm.SUDOWOODO]: "0129",
   [Pkm.EKANS]: "0129",
   [Pkm.ARBOK]: "0129",
   [Pkm.CASTFORM]: "0351",
   [Pkm.CASTFORM_SUN]: "0351-0001",
   [Pkm.CASTFORM_RAIN]: "0351-0002",
   [Pkm.CASTFORM_HAIL]: "0351-0003"
}