export enum SpecialGameRule {
  EVERYONE_IS_HERE = "EVERYONE_IS_HERE",
  UNIQUE_STARTER = "UNIQUE_STARTER",
  OMELETTE_COOK = "OMELETTE_COOK",
  SYNERGY_WHEEL = "SYNERGY_WHEEL",
  DITTO_PARTY = "DITTO_PARTY",
  RARE_IS_EXPENSIVE = "RARE_IS_EXPENSIVE",
  GOTTA_CATCH_EM_ALL = "GOTTA_CATCH_EM_ALL",
  BUYER_FEVER = "BUYER_FEVER",
  TECHNOLOGIC = "TECHNOLOGIC",
  SIX_PACK = "SIX_PACK",
  NINE_LIVES = "NINE_LIVES",
  CROWDED = "CROWDED",
  KECLEONS_SHOP = "KECLEONS_SHOP"
}
