export enum Synergy {
  NORMAL = 'normal',
  GRASS = 'grass',
  FIRE = 'fire',
  WATER = 'water',
  ELECTRIC = 'electric',
  FIGHTING = 'fighting',
  PSYCHIC = 'psychic',
  DARK = 'dark',
  METAL = 'metal',
  GROUND = 'ground',
  POISON = 'poison',
  DRAGON = 'dragon',
  FIELD = 'field',
  MONSTER = 'monster',
  HUMAN = 'human',
  AQUATIC = 'aquatic',
  BUG = 'bug',
  FLYING = 'flying',
  FLORA = 'flora',
  MINERAL = 'mineral',
  GHOST = 'ghost',
  FAIRY = 'fairy',
  ICE = 'ice',
  FOSSIL = 'fossil',
  SOUND = 'sound'
}