export enum WandererBehavior {
  RUN_THROUGH = "RUN_THROUGH",
  SPECTATE = "SPECTATE"
}

export enum WandererType {
  CATCHABLE = "CATCHABLE",
  UNOWN = "UNOWN",
  UNOWN_SPELL = "UNOWN_SPELL",
  DIALOG = "DIALOG",
  OUTLAW = "OUTLAW",
  CROAGUNK_TRADE = "CROAGUNK_TRADE",
  KECLEON_ARMORY_ASSIST = "KECLEON_ARMORY_ASSIST"
}
