// This file is generated by gen/generate-ability-definition-registry.ts.
// The development watcher and production build keep it up to date automatically.

import aquaRingDefinition from "./aqua-ring"
import blizzardDefinition from "./blizzard"
import freezingGlareDefinition from "./freezing-glare"
import protectDefinition from "./protect"
import struggleBugDefinition from "./struggle-bug"

export const AbilityDefinitions = Object.freeze({
  [aquaRingDefinition.ability]: aquaRingDefinition,
  [blizzardDefinition.ability]: blizzardDefinition,
  [freezingGlareDefinition.ability]: freezingGlareDefinition,
  [protectDefinition.ability]: protectDefinition,
  [struggleBugDefinition.ability]: struggleBugDefinition
})
