// This file is generated by gen/generate-ability-definition-registry.ts.
// The development watcher and production build keep it up to date automatically.

import aquaRingDefinition from "./aqua-ring"
import blizzardDefinition from "./blizzard"

export const AbilityDefinitions = Object.freeze({
  [aquaRingDefinition.ability]: aquaRingDefinition,
  [blizzardDefinition.ability]: blizzardDefinition
})
