const EFFECTS = Object.freeze({
  INGRAIN: "INGRAIN",
  GROWTH: "GROWTH",
  SPORE: "SPORE",
  BLAZE: "BLAZE",
  DROUGHT: "DROUGHT",
  DRIZZLE: "DRIZZLE",
  RAIN_DANCE: "RAIN_DANCE",
  PRIMORDIAL_SEA: "PRIMORDIAL_SEA",
  STRENGTH: "STRENGTH",
  PURE_POWER: "PURE_POWER",
  AGILITY: "AGILITY",
  REVENGE: "REVENGE",
  PUNISHMENT: "PUNISHMENT",
  PSYWAVE: "PSYWAVE",
  MAGIC_ROOM: "MAGIC_ROOM",
  MEAN_LOOK: "MEAN_LOOK",
  SCARY_FACE: "SCARY_FACE",
  IRON_DEFENSE: "IRON_DEFENSE",
  AUTOTOMIZE: "AUTOTOMIZE",
  SPIKES: "SPIKES",
  STEALTH_ROCK: "STEALTH_ROCK",
  SANDSTORM: "SANDSTORM",
  POISON_GAS: "POISON_GAS",
  TOXIC:"TOXIC",
  INTIMIDATE:"INTIMIDATE",
  DRACO_METEOR:"DRACO_METEOR",
  WORK_UP:"WORK_UP",
  RAGE:"RAGE",
  ANGER_POINT:"ANGER_POINT",
  PURSUIT:"PURSUIT",
  BRUTAL_SWING:"BRUTAL_SWING",
  POWER_TRIP:"POWER_TRIP",
  MEDITATE:"MEDITATE",
  FOCUS_ENERGY:"FOCUS_ENERGY",
  SWARM:"SWARM",
  STICKY_WEB:"STICKY_WEB",
  HYDO_CANNON:"HYDRO_CANNON",
  RAZOR_WIND:"RAZOR_WIND",
  HURRICANE:"HURRICANE",
  RAIN_DISH:"RAIN_DISH",
  FLOWER_SHIELD:"FLOWER_SHIELD",
  BATTLE_ARMOR:"BATTLE_ARMOR",
  PHANTOM_FORCE:"PHANTOM_FORCE",
  ATTRACT:"ATTRACT",
  BABY_DOLL_EYES:"BABY_DOLL_EYES"
});

const TYPE = Object.freeze({
  NORMAL: "NORMAL",
  GRASS: "GRASS",
  FIRE: "FIRE",
  WATER: "WATER",
  ELECTRIC: "ELECTRIC",
  FIGHTING: "FIGHTING",
  PSYCHIC: "PSYCHIC",
  DARK: "DARK",
  METAL: "METAL",
  GROUND: "GROUND",
  POISON: "POISON",
  DRAGON: "DRAGON",
  FIELD: "FIELD",
  MONSTER: "MONSTER",
  HUMAN: "HUMAN",
  AQUATIC: "AQUATIC",
  BUG: "BUG",
  FLYING: "FLYING",
  FLORA: "FLORA",
  MINERAL: "MINERAL",
  AMORPH: "AMORPH",
  FAIRY: "FAIRY"
});

const RARITY = Object.freeze({
  COMMON: "COMMON",
  UNCOMMON: "UNCOMMON",
  RARE: "RARE",
  EPIC: "EPIC",
  LEGENDARY: "LEGENDARY"
});

const COST = Object.freeze({
  COMMON: 1,
  UNCOMMON: 2,
  RARE: 3,
  EPIC: 4,
  LEGENDARY: 5
});

const EXP_TABLE = Object.freeze({
  1: 0,
  2: 2,
  3: 6,
  4: 10,
  5: 20,
  6: 32,
  7: 50,
  8: 70
});

const STATE = Object.freeze({
  FIGHT: "FIGHT",
  PICK: "PICK"
});

const STATE_TYPE = Object.freeze({
  MOVING: "MOVING",
  ATTACKING: "ATTACKING"
});

const ORIENTATION = Object.freeze({
  DOWNLEFT: "DOWNLEFT",
  LEFT: "LEFT",
  UPLEFT: "UPLEFT",
  UP: "UP",
  UPRIGHT: "UPRIGHT",
  RIGHT: "RIGHT",
  DOWNRIGHT: "DOWNRIGHT",
  DOWN: "DOWN"
});

module.exports = { TYPE, RARITY, COST, EXP_TABLE, STATE, STATE_TYPE, ORIENTATION, EFFECTS};