const SCENARIOS =
{
  "WATER1": {
    "steps": [
      {
        "roundsRequired": 0,
        "board": [
          {
            "name":"hoppip",
            "x":3,
            "y":2
          },
          {
            "name":"hoppip",
            "x":4,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"hoppip",
            "x":4,
            "y":1
          },
          {
            "name":"chikorita",
            "x":3,
            "y":1
          },
          {
            "name":"caterpie",
            "x":4,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"horsea",
            "x":5,
            "y":1
          },
          {
            "name":"squirtle",
            "x":4,
            "y":2
          },
          {
            "name":"mudkip",
            "x":4,
            "y":3
          },
          {
            "name":"piplup",
            "x":5,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"horsea",
            "x":4,
            "y":1
          },
          {
            "name":"squirtle",
            "x":4,
            "y":2
          },
          {
            "name":"mudkip",
            "x":4,
            "y":3
          },
          {
            "name":"marill",
            "x":3,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"horsea",
            "x":4,
            "y":1
          },
          {
            "name":"squirtle",
            "x":4,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":4,
            "y":3
          },
          {
            "name":"marill",
            "x":3,
            "y":2
          },
          {
            "name":"totodile",
            "x":3,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"seadra",
            "x":4,
            "y":1
          },
          {
            "name":"wartortle",
            "x":4,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":4,
            "y":3
          },
          {
            "name":"marill",
            "x":3,
            "y":2
          },
          {
            "name":"totodile",
            "x":3,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"seadra",
            "x":4,
            "y":1
          },
          {
            "name":"wartortle",
            "x":4,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":4,
            "y":3
          },
          {
            "name":"marill",
            "x":3,
            "y":2
          },
          {
            "name":"poliwag",
            "x":5,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"wartortle",
            "x":2,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":3
          },
          {
            "name":"marill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwag",
            "x":1,
            "y":1
          },
          {
            "name":"croconaw",
            "x":1,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"wartortle",
            "x":2,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":3
          },
          {
            "name":"marill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":1
          },
          {
            "name":"croconaw",
            "x":1,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 4,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"wartortle",
            "x":2,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":3
          },
          {
            "name":"marill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":1
          },
          {
            "name":"croconaw",
            "x":1,
            "y":3
          },
          {
            "name":"lombre",
            "x":2,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 4,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"wartortle",
            "x":2,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":3
          },
          {
            "name":"marill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":1
          },
          {
            "name":"croconaw",
            "x":1,
            "y":3
          },
          {
            "name":"lombre",
            "x":2,
            "y":1
          },
          {
            "name":"prinplup",
            "x":3,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 5,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"wartortle",
            "x":2,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":3
          },
          {
            "name":"marill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":1
          },
          {
            "name":"croconaw",
            "x":1,
            "y":3
          },
          {
            "name":"lombre",
            "x":2,
            "y":1
          },
          {
            "name":"prinplup",
            "x":3,
            "y":2
          },
          {
            "name":"spheal",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"wartortle",
            "x":2,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":3
          },
          {
            "name":"marill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":1
          },
          {
            "name":"croconaw",
            "x":1,
            "y":3
          },
          {
            "name":"lombre",
            "x":2,
            "y":1
          },
          {
            "name":"prinplup",
            "x":3,
            "y":2
          },
          {
            "name":"sealeo",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 5,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"blastoise",
            "x":2,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":3
          },
          {
            "name":"marill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":1
          },
          {
            "name":"croconaw",
            "x":1,
            "y":3
          },
          {
            "name":"lombre",
            "x":2,
            "y":1
          },
          {
            "name":"prinplup",
            "x":3,
            "y":2
          },
          {
            "name":"sealeo",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"blastoise",
            "x":2,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":3
          },
          {
            "name":"azumarill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":1
          },
          {
            "name":"croconaw",
            "x":1,
            "y":3
          },
          {
            "name":"lombre",
            "x":2,
            "y":1
          },
          {
            "name":"prinplup",
            "x":3,
            "y":2
          },
          {
            "name":"sealeo",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"blastoise",
            "x":2,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":3
          },
          {
            "name":"azumarill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":1
          },
          {
            "name":"croconaw",
            "x":1,
            "y":3
          },
          {
            "name":"lombre",
            "x":2,
            "y":1
          },
          {
            "name":"empoleon",
            "x":3,
            "y":2
          },
          {
            "name":"sealeo",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"blastoise",
            "x":2,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":3
          },
          {
            "name":"azumarill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":1
          },
          {
            "name":"feraligatr",
            "x":1,
            "y":3
          },
          {
            "name":"lombre",
            "x":2,
            "y":1
          },
          {
            "name":"empoleon",
            "x":3,
            "y":2
          },
          {
            "name":"sealeo",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"blastoise",
            "x":2,
            "y":2
          },
          {
            "name":"swampert",
            "x":2,
            "y":3
          },
          {
            "name":"azumarill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":1
          },
          {
            "name":"feraligatr",
            "x":1,
            "y":3
          },
          {
            "name":"lombre",
            "x":2,
            "y":1
          },
          {
            "name":"empoleon",
            "x":3,
            "y":2
          },
          {
            "name":"sealeo",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"blastoise",
            "x":2,
            "y":2
          },
          {
            "name":"swampert",
            "x":2,
            "y":3
          },
          {
            "name":"azumarill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":1
          },
          {
            "name":"feraligatr",
            "x":1,
            "y":3
          },
          {
            "name":"ludicolo",
            "x":2,
            "y":1
          },
          {
            "name":"empoleon",
            "x":3,
            "y":2
          },
          {
            "name":"sealeo",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"blastoise",
            "x":2,
            "y":2
          },
          {
            "name":"swampert",
            "x":2,
            "y":3
          },
          {
            "name":"azumarill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwrath",
            "x":1,
            "y":1
          },
          {
            "name":"feraligatr",
            "x":1,
            "y":3
          },
          {
            "name":"ludicolo",
            "x":2,
            "y":1
          },
          {
            "name":"empoleon",
            "x":3,
            "y":2
          },
          {
            "name":"sealeo",
            "x":0,
            "y":2
          }
        ]
      }
    ]
  },
  "FIRE1": {
    "steps": [
      {
        "roundsRequired": 0,
        "board": [
          {
            "name":"igglybuff",
            "x":3,
            "y":2
          },
          {
            "name":"igglybuff",
            "x":4,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"igglybuff",
            "x":4,
            "y":1
          },
          {
            "name":"azurill",
            "x":3,
            "y":1
          },
          {
            "name":"cleffa",
            "x":4,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"cyndaquil",
            "x":5,
            "y":1
          },
          {
            "name":"charmander",
            "x":3,
            "y":3
          },
          {
            "name":"chimchar",
            "x":4,
            "y":3
          },
          {
            "name":"torchic",
            "x":5,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"cyndaquil",
            "x":4,
            "y":1
          },
          {
            "name":"charmeleon",
            "x":5,
            "y":3
          },
          {
            "name":"chimchar",
            "x":4,
            "y":3
          },
          {
            "name":"torchic",
            "x":3,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"cyndaquil",
            "x":4,
            "y":1
          },
          {
            "name":"charmeleon",
            "x":5,
            "y":3
          },
          {
            "name":"chimchar",
            "x":4,
            "y":3
          },
          {
            "name":"torchic",
            "x":3,
            "y":3
          },
          {
            "name":"flareon",
            "x":2,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"quilava",
            "x":4,
            "y":1
          },
          {
            "name":"charmeleon",
            "x":5,
            "y":3
          },
          {
            "name":"chimchar",
            "x":4,
            "y":3
          },
          {
            "name":"torchic",
            "x":3,
            "y":3
          },
          {
            "name":"flareon",
            "x":2,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"quilava",
            "x":4,
            "y":1
          },
          {
            "name":"charmeleon",
            "x":5,
            "y":3
          },
          {
            "name":"chimchar",
            "x":4,
            "y":3
          },
          {
            "name":"combusken",
            "x":3,
            "y":3
          },
          {
            "name":"flareon",
            "x":2,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"quilava",
            "x":2,
            "y":1
          },
          {
            "name":"charmeleon",
            "x":0,
            "y":3
          },
          {
            "name":"chimchar",
            "x":1,
            "y":3
          },
          {
            "name":"combusken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machop",
            "x":4,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"quilava",
            "x":2,
            "y":1
          },
          {
            "name":"charmeleon",
            "x":0,
            "y":3
          },
          {
            "name":"monferno",
            "x":1,
            "y":3
          },
          {
            "name":"combusken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machop",
            "x":4,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 4,
        "board":
        [
          {
            "name":"quilava",
            "x":2,
            "y":1
          },
          {
            "name":"charmeleon",
            "x":0,
            "y":3
          },
          {
            "name":"monferno",
            "x":1,
            "y":3
          },
          {
            "name":"combusken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machop",
            "x":4,
            "y":3
          },
          {
            "name":"magby",
            "x":1,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 4,
        "board":
        [
          {
            "name":"quilava",
            "x":2,
            "y":1
          },
          {
            "name":"charmeleon",
            "x":0,
            "y":3
          },
          {
            "name":"infernape",
            "x":1,
            "y":3
          },
          {
            "name":"blaziken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machoke",
            "x":4,
            "y":3
          },
          {
            "name":"magby",
            "x":1,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 5,
        "board":
        [
          {
            "name":"quilava",
            "x":2,
            "y":1
          },
          {
            "name":"charmeleon",
            "x":0,
            "y":3
          },
          {
            "name":"infernape",
            "x":1,
            "y":3
          },
          {
            "name":"blaziken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machoke",
            "x":4,
            "y":3
          },
          {
            "name":"magmar",
            "x":1,
            "y":1
          },
          {
            "name":"numel",
            "x":5,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"quilava",
            "x":1,
            "y":1
          },
          {
            "name":"charmeleon",
            "x":0,
            "y":3
          },
          {
            "name":"infernape",
            "x":1,
            "y":3
          },
          {
            "name":"blaziken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machoke",
            "x":4,
            "y":3
          },
          {
            "name":"magmar",
            "x":3,
            "y":1
          },
          {
            "name":"numel",
            "x":5,
            "y":3
          },
          {
            "name":"riolu",
            "x":2,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 5,
        "board":
        [
          {
            "name":"quilava",
            "x":1,
            "y":1
          },
          {
            "name":"charizard",
            "x":0,
            "y":3
          },
          {
            "name":"infernape",
            "x":1,
            "y":3
          },
          {
            "name":"blaziken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machoke",
            "x":4,
            "y":3
          },
          {
            "name":"magmar",
            "x":3,
            "y":1
          },
          {
            "name":"numel",
            "x":5,
            "y":3
          },
          {
            "name":"riolu",
            "x":2,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"quilava",
            "x":1,
            "y":1
          },
          {
            "name":"charizard",
            "x":0,
            "y":3
          },
          {
            "name":"infernape",
            "x":1,
            "y":3
          },
          {
            "name":"blaziken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machoke",
            "x":4,
            "y":3
          },
          {
            "name":"magmar",
            "x":3,
            "y":1
          },
          {
            "name":"camerupt",
            "x":5,
            "y":3
          },
          {
            "name":"riolu",
            "x":2,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"quilava",
            "x":1,
            "y":1
          },
          {
            "name":"charizard",
            "x":0,
            "y":3
          },
          {
            "name":"infernape",
            "x":1,
            "y":3
          },
          {
            "name":"blaziken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machoke",
            "x":4,
            "y":3
          },
          {
            "name":"magmar",
            "x":3,
            "y":1
          },
          {
            "name":"camerupt",
            "x":5,
            "y":3
          },
          {
            "name":"lucario",
            "x":2,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"typhlosion",
            "x":1,
            "y":1
          },
          {
            "name":"charizard",
            "x":0,
            "y":3
          },
          {
            "name":"infernape",
            "x":1,
            "y":3
          },
          {
            "name":"blaziken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machoke",
            "x":4,
            "y":3
          },
          {
            "name":"magmar",
            "x":3,
            "y":1
          },
          {
            "name":"camerupt",
            "x":5,
            "y":3
          },
          {
            "name":"lucario",
            "x":2,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"typhlosion",
            "x":1,
            "y":1
          },
          {
            "name":"charizard",
            "x":0,
            "y":3
          },
          {
            "name":"infernape",
            "x":1,
            "y":3
          },
          {
            "name":"blaziken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machamp",
            "x":4,
            "y":3
          },
          {
            "name":"magmar",
            "x":3,
            "y":1
          },
          {
            "name":"camerupt",
            "x":5,
            "y":3
          },
          {
            "name":"lucario",
            "x":2,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"typhlosion",
            "x":1,
            "y":1
          },
          {
            "name":"charizard",
            "x":0,
            "y":3
          },
          {
            "name":"infernape",
            "x":1,
            "y":3
          },
          {
            "name":"blaziken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machamp",
            "x":4,
            "y":3
          },
          {
            "name":"magmortar",
            "x":3,
            "y":1
          },
          {
            "name":"camerupt",
            "x":5,
            "y":3
          },
          {
            "name":"lucario",
            "x":2,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"typhlosion",
            "x":1,
            "y":1
          },
          {
            "name":"charizard",
            "x":0,
            "y":3
          },
          {
            "name":"infernape",
            "x":1,
            "y":3
          },
          {
            "name":"blaziken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machamp",
            "x":4,
            "y":3
          },
          {
            "name":"magmortar",
            "x":3,
            "y":1
          },
          {
            "name":"megacamerupt",
            "x":5,
            "y":3
          },
          {
            "name":"lucario",
            "x":2,
            "y":1
          }
        ]
      }
    ]
  },
  "POISON1": {
    "steps": [
      {
        "roundsRequired": 0,
        "board": [
          {
            "name":"zubat",
            "x":3,
            "y":2
          },
          {
            "name":"geodude",
            "x":4,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"zubat",
            "x":4,
            "y":1
          },
          {
            "name":"geodude",
            "x":3,
            "y":1
          },
          {
            "name":"weedle",
            "x":4,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"zubat",
            "x":5,
            "y":1
          },
          {
            "name":"weedle",
            "x":3,
            "y":3
          },
          {
            "name":"nidoranF",
            "x":4,
            "y":3
          },
          {
            "name":"nidoranM",
            "x":5,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"golbat",
            "x":4,
            "y":1
          },
          {
            "name":"weedle",
            "x":5,
            "y":3
          },
          {
            "name":"nidoranF",
            "x":4,
            "y":3
          },
          {
            "name":"nidoranM",
            "x":3,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"golbat",
            "x":4,
            "y":1
          },
          {
            "name":"weedle",
            "x":5,
            "y":3
          },
          {
            "name":"nidoranF",
            "x":4,
            "y":3
          },
          {
            "name":"nidoranM",
            "x":3,
            "y":3
          },
          {
            "name":"bulbasaur",
            "x":2,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"golbat",
            "x":4,
            "y":1
          },
          {
            "name":"weedle",
            "x":5,
            "y":3
          },
          {
            "name":"nidoranF",
            "x":4,
            "y":3
          },
          {
            "name":"nidoranM",
            "x":3,
            "y":3
          },
          {
            "name":"ivysaur",
            "x":2,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"golbat",
            "x":4,
            "y":1
          },
          {
            "name":"weedle",
            "x":5,
            "y":3
          },
          {
            "name":"nidorina",
            "x":4,
            "y":3
          },
          {
            "name":"nidorino",
            "x":3,
            "y":3
          },
          {
            "name":"ivysaur",
            "x":2,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"golbat",
            "x":2,
            "y":1
          },
          {
            "name":"weedle",
            "x":0,
            "y":3
          },
          {
            "name":"nidorina",
            "x":1,
            "y":3
          },
          {
            "name":"nidorino",
            "x":2,
            "y":3
          },
          {
            "name":"ivysaur",
            "x":3,
            "y":3
          },
          {
            "name":"gastly",
            "x":4,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"golbat",
            "x":2,
            "y":1
          },
          {
            "name":"kakuna",
            "x":0,
            "y":3
          },
          {
            "name":"nidorina",
            "x":1,
            "y":3
          },
          {
            "name":"nidorino",
            "x":2,
            "y":3
          },
          {
            "name":"ivysaur",
            "x":3,
            "y":3
          },
          {
            "name":"gastly",
            "x":4,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 4,
        "board":
        [
          {
            "name":"golbat",
            "x":2,
            "y":1
          },
          {
            "name":"kakuna",
            "x":0,
            "y":3
          },
          {
            "name":"nidorina",
            "x":1,
            "y":3
          },
          {
            "name":"nidorino",
            "x":2,
            "y":3
          },
          {
            "name":"ivysaur",
            "x":3,
            "y":3
          },
          {
            "name":"gastly",
            "x":4,
            "y":1
          },
          {
            "name":"duskull",
            "x":1,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 4,
        "board":
        [
          {
            "name":"golbat",
            "x":2,
            "y":1
          },
          {
            "name":"kakuna",
            "x":0,
            "y":3
          },
          {
            "name":"nidorina",
            "x":1,
            "y":3
          },
          {
            "name":"nidorino",
            "x":2,
            "y":3
          },
          {
            "name":"ivysaur",
            "x":3,
            "y":3
          },
          {
            "name":"gastly",
            "x":4,
            "y":1
          },
          {
            "name":"dusclops",
            "x":1,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 5,
        "board":
        [
          {
            "name":"crobat",
            "x":2,
            "y":1
          },
          {
            "name":"kakuna",
            "x":0,
            "y":3
          },
          {
            "name":"nidorina",
            "x":1,
            "y":3
          },
          {
            "name":"nidorino",
            "x":2,
            "y":3
          },
          {
            "name":"ivysaur",
            "x":3,
            "y":3
          },
          {
            "name":"haunter",
            "x":4,
            "y":1
          },
          {
            "name":"dusclops",
            "x":1,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"crobat",
            "x":2,
            "y":1
          },
          {
            "name":"kakuna",
            "x":0,
            "y":3
          },
          {
            "name":"nidorina",
            "x":1,
            "y":3
          },
          {
            "name":"nidorino",
            "x":2,
            "y":3
          },
          {
            "name":"ivysaur",
            "x":3,
            "y":3
          },
          {
            "name":"haunter",
            "x":4,
            "y":1
          },
          {
            "name":"dusclops",
            "x":1,
            "y":1
          },
          {
            "name":"ralts",
            "x":3,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 5,
        "board":
        [
          {
            "name":"crobat",
            "x":2,
            "y":1
          },
          {
            "name":"kakuna",
            "x":0,
            "y":3
          },
          {
            "name":"nidorina",
            "x":1,
            "y":3
          },
          {
            "name":"nidorino",
            "x":2,
            "y":3
          },
          {
            "name":"ivysaur",
            "x":3,
            "y":3
          },
          {
            "name":"haunter",
            "x":4,
            "y":1
          },
          {
            "name":"dusclops",
            "x":1,
            "y":1
          },
          {
            "name":"kirlia",
            "x":3,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"crobat",
            "x":2,
            "y":1
          },
          {
            "name":"beedrill",
            "x":0,
            "y":3
          },
          {
            "name":"nidorina",
            "x":1,
            "y":3
          },
          {
            "name":"nidorino",
            "x":2,
            "y":3
          },
          {
            "name":"ivysaur",
            "x":3,
            "y":3
          },
          {
            "name":"haunter",
            "x":4,
            "y":1
          },
          {
            "name":"dusclops",
            "x":1,
            "y":1
          },
          {
            "name":"gardevoir",
            "x":3,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"crobat",
            "x":2,
            "y":1
          },
          {
            "name":"beedrill",
            "x":0,
            "y":3
          },
          {
            "name":"nidorina",
            "x":1,
            "y":3
          },
          {
            "name":"nidorino",
            "x":2,
            "y":3
          },
          {
            "name":"venusaur",
            "x":3,
            "y":3
          },
          {
            "name":"haunter",
            "x":4,
            "y":1
          },
          {
            "name":"dusclops",
            "x":1,
            "y":1
          },
          {
            "name":"gardevoir",
            "x":3,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"crobat",
            "x":2,
            "y":1
          },
          {
            "name":"beedrill",
            "x":0,
            "y":3
          },
          {
            "name":"nidoqueen",
            "x":1,
            "y":3
          },
          {
            "name":"nidorino",
            "x":2,
            "y":3
          },
          {
            "name":"venusaur",
            "x":3,
            "y":3
          },
          {
            "name":"haunter",
            "x":4,
            "y":1
          },
          {
            "name":"dusclops",
            "x":1,
            "y":1
          },
          {
            "name":"gardevoir",
            "x":3,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"crobat",
            "x":2,
            "y":1
          },
          {
            "name":"beedrill",
            "x":0,
            "y":3
          },
          {
            "name":"nidoqueen",
            "x":1,
            "y":3
          },
          {
            "name":"nidorino",
            "x":2,
            "y":3
          },
          {
            "name":"venusaur",
            "x":3,
            "y":3
          },
          {
            "name":"haunter",
            "x":4,
            "y":1
          },
          {
            "name":"dusclops",
            "x":1,
            "y":1
          },
          {
            "name":"gardevoir",
            "x":3,
            "y":1
          },
          {
            "name":"bayleef",
            "x":5,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"crobat",
            "x":2,
            "y":1
          },
          {
            "name":"beedrill",
            "x":0,
            "y":3
          },
          {
            "name":"nidoqueen",
            "x":1,
            "y":3
          },
          {
            "name":"nidoking",
            "x":2,
            "y":3
          },
          {
            "name":"venusaur",
            "x":3,
            "y":3
          },
          {
            "name":"haunter",
            "x":4,
            "y":1
          },
          {
            "name":"dusclops",
            "x":1,
            "y":1
          },
          {
            "name":"gardevoir",
            "x":3,
            "y":1
          },
          {
            "name":"bayleef",
            "x":5,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"crobat",
            "x":2,
            "y":1
          },
          {
            "name":"beedrill",
            "x":0,
            "y":3
          },
          {
            "name":"nidoqueen",
            "x":1,
            "y":3
          },
          {
            "name":"nidoking",
            "x":2,
            "y":3
          },
          {
            "name":"venusaur",
            "x":3,
            "y":3
          },
          {
            "name":"gengar",
            "x":4,
            "y":1
          },
          {
            "name":"dusclops",
            "x":1,
            "y":1
          },
          {
            "name":"gardevoir",
            "x":3,
            "y":1
          },
          {
            "name":"meganium",
            "x":5,
            "y":3
          }
        ]
      }
    ]
  }
}


module.exports = SCENARIOS;
