const SCENARIOS = 
{
  "WATER1": {
    "steps": [
      {
        "roundsRequired": 0,
        "board": [
          {
            "name":"hoppip",
            "x":3,
            "y":1
          },
          {
            "name":"hoppip",
            "x":4,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"hoppip",
            "x":4,
            "y":0
          },
          {
            "name":"chikorita",
            "x":3,
            "y":0
          },
          {
            "name":"carterpie",
            "x":4,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"horsea",
            "x":5,
            "y":0
          },
          {
            "name":"squirtle",
            "x":4,
            "y":1
          },
          {
            "name":"mudkip",
            "x":4,
            "y":2
          },
          {
            "name":"piplup",
            "x":5,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"horsea",
            "x":4,
            "y":0
          },
          {
            "name":"squirtle",
            "x":4,
            "y":1
          },
          {
            "name":"mudkip",
            "x":4,
            "y":2
          },
          {
            "name":"marill",
            "x":3,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"horsea",
            "x":4,
            "y":0
          },
          {
            "name":"squirtle",
            "x":4,
            "y":1
          },
          {
            "name":"marshtomp",
            "x":4,
            "y":2
          },
          {
            "name":"marill",
            "x":3,
            "y":1
          },
          {
            "name":"totodile",
            "x":3,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"seadra",
            "x":4,
            "y":0
          },
          {
            "name":"wartortle",
            "x":4,
            "y":1
          },
          {
            "name":"marshtomp",
            "x":4,
            "y":2
          },
          {
            "name":"marill",
            "x":3,
            "y":1
          },
          {
            "name":"totodile",
            "x":3,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"seadra",
            "x":4,
            "y":0
          },
          {
            "name":"wartortle",
            "x":4,
            "y":1
          },
          {
            "name":"marshtomp",
            "x":4,
            "y":2
          },
          {
            "name":"marill",
            "x":3,
            "y":1
          },
          {
            "name":"poliwag",
            "x":5,
            "y":0
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":0
          },
          {
            "name":"wartortle",
            "x":2,
            "y":1
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":2
          },
          {
            "name":"marill",
            "x":1,
            "y":1
          },
          {
            "name":"poliwag",
            "x":1,
            "y":0
          },
          {
            "name":"croconaw",
            "x":1,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":0
          },
          {
            "name":"wartortle",
            "x":2,
            "y":1
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":2
          },
          {
            "name":"marill",
            "x":1,
            "y":1
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":0
          },
          {
            "name":"croconaw",
            "x":1,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 4,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":0
          },
          {
            "name":"wartortle",
            "x":2,
            "y":1
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":2
          },
          {
            "name":"marill",
            "x":1,
            "y":1
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":0
          },
          {
            "name":"croconaw",
            "x":1,
            "y":2
          },
          {
            "name":"lombre",
            "x":2,
            "y":0
          }
        ]
      },
      {
        "roundsRequired": 4,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":0
          },
          {
            "name":"wartortle",
            "x":2,
            "y":1
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":2
          },
          {
            "name":"marill",
            "x":1,
            "y":1
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":0
          },
          {
            "name":"croconaw",
            "x":1,
            "y":2
          },
          {
            "name":"lombre",
            "x":2,
            "y":0
          },
          {
            "name":"prinplup",
            "x":3,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 5,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":0
          },
          {
            "name":"wartortle",
            "x":2,
            "y":1
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":2
          },
          {
            "name":"marill",
            "x":1,
            "y":1
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":0
          },
          {
            "name":"croconaw",
            "x":1,
            "y":2
          },
          {
            "name":"lombre",
            "x":2,
            "y":0
          },
          {
            "name":"prinplup",
            "x":3,
            "y":1
          },
          {
            "name":"spheal",
            "x":0,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":0
          },
          {
            "name":"wartortle",
            "x":2,
            "y":1
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":2
          },
          {
            "name":"marill",
            "x":1,
            "y":1
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":0
          },
          {
            "name":"croconaw",
            "x":1,
            "y":2
          },
          {
            "name":"lombre",
            "x":2,
            "y":0
          },
          {
            "name":"prinplup",
            "x":3,
            "y":1
          },
          {
            "name":"sealeo",
            "x":0,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 5,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":0
          },
          {
            "name":"blastoise",
            "x":2,
            "y":1
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":2
          },
          {
            "name":"marill",
            "x":1,
            "y":1
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":0
          },
          {
            "name":"croconaw",
            "x":1,
            "y":2
          },
          {
            "name":"lombre",
            "x":2,
            "y":0
          },
          {
            "name":"prinplup",
            "x":3,
            "y":1
          },
          {
            "name":"sealeo",
            "x":0,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":0
          },
          {
            "name":"blastoise",
            "x":2,
            "y":1
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":2
          },
          {
            "name":"azumarill",
            "x":1,
            "y":1
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":0
          },
          {
            "name":"croconaw",
            "x":1,
            "y":2
          },
          {
            "name":"lombre",
            "x":2,
            "y":0
          },
          {
            "name":"prinplup",
            "x":3,
            "y":1
          },
          {
            "name":"sealeo",
            "x":0,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":0
          },
          {
            "name":"blastoise",
            "x":2,
            "y":1
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":2
          },
          {
            "name":"azumarill",
            "x":1,
            "y":1
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":0
          },
          {
            "name":"croconaw",
            "x":1,
            "y":2
          },
          {
            "name":"lombre",
            "x":2,
            "y":0
          },
          {
            "name":"empoleon",
            "x":3,
            "y":1
          },
          {
            "name":"sealeo",
            "x":0,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":0
          },
          {
            "name":"blastoise",
            "x":2,
            "y":1
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":2
          },
          {
            "name":"azumarill",
            "x":1,
            "y":1
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":0
          },
          {
            "name":"feraligatr",
            "x":1,
            "y":2
          },
          {
            "name":"lombre",
            "x":2,
            "y":0
          },
          {
            "name":"empoleon",
            "x":3,
            "y":1
          },
          {
            "name":"sealeo",
            "x":0,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":0
          },
          {
            "name":"blastoise",
            "x":2,
            "y":1
          },
          {
            "name":"swampert",
            "x":2,
            "y":2
          },
          {
            "name":"azumarill",
            "x":1,
            "y":1
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":0
          },
          {
            "name":"feraligatr",
            "x":1,
            "y":2
          },
          {
            "name":"lombre",
            "x":2,
            "y":0
          },
          {
            "name":"empoleon",
            "x":3,
            "y":1
          },
          {
            "name":"sealeo",
            "x":0,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":0
          },
          {
            "name":"blastoise",
            "x":2,
            "y":1
          },
          {
            "name":"swampert",
            "x":2,
            "y":2
          },
          {
            "name":"azumarill",
            "x":1,
            "y":1
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":0
          },
          {
            "name":"feraligatr",
            "x":1,
            "y":2
          },
          {
            "name":"ludicolo",
            "x":2,
            "y":0
          },
          {
            "name":"empoleon",
            "x":3,
            "y":1
          },
          {
            "name":"sealeo",
            "x":0,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":0
          },
          {
            "name":"blastoise",
            "x":2,
            "y":1
          },
          {
            "name":"swampert",
            "x":2,
            "y":2
          },
          {
            "name":"azumarill",
            "x":1,
            "y":1
          },
          {
            "name":"poliwrath",
            "x":1,
            "y":0
          },
          {
            "name":"feraligatr",
            "x":1,
            "y":2
          },
          {
            "name":"ludicolo",
            "x":2,
            "y":0
          },
          {
            "name":"empoleon",
            "x":3,
            "y":1
          },
          {
            "name":"sealeo",
            "x":0,
            "y":1
          }
        ]
      }
    ]
  }
}
  