const SCENARIOS =
{
  "WATER1": {
    "steps": [
      {
        "roundsRequired": 0,
        "board": [
          {
            "name":"hoppip",
            "x":3,
            "y":2
          },
          {
            "name":"hoppip",
            "x":4,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"hoppip",
            "x":4,
            "y":1
          },
          {
            "name":"chikorita",
            "x":3,
            "y":1
          },
          {
            "name":"caterpie",
            "x":4,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"horsea",
            "x":5,
            "y":1
          },
          {
            "name":"squirtle",
            "x":4,
            "y":2
          },
          {
            "name":"mudkip",
            "x":4,
            "y":3
          },
          {
            "name":"piplup",
            "x":5,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"horsea",
            "x":4,
            "y":1
          },
          {
            "name":"squirtle",
            "x":4,
            "y":2
          },
          {
            "name":"mudkip",
            "x":4,
            "y":3
          },
          {
            "name":"marill",
            "x":3,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"horsea",
            "x":4,
            "y":1
          },
          {
            "name":"squirtle",
            "x":4,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":4,
            "y":3
          },
          {
            "name":"marill",
            "x":3,
            "y":2
          },
          {
            "name":"totodile",
            "x":3,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"seadra",
            "x":4,
            "y":1
          },
          {
            "name":"wartortle",
            "x":4,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":4,
            "y":3
          },
          {
            "name":"marill",
            "x":3,
            "y":2
          },
          {
            "name":"totodile",
            "x":3,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"seadra",
            "x":4,
            "y":1
          },
          {
            "name":"wartortle",
            "x":4,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":4,
            "y":3
          },
          {
            "name":"marill",
            "x":3,
            "y":2
          },
          {
            "name":"poliwag",
            "x":5,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"wartortle",
            "x":2,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":3
          },
          {
            "name":"marill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwag",
            "x":1,
            "y":1
          },
          {
            "name":"croconaw",
            "x":1,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"wartortle",
            "x":2,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":3
          },
          {
            "name":"marill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":1
          },
          {
            "name":"croconaw",
            "x":1,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 4,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"wartortle",
            "x":2,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":3
          },
          {
            "name":"marill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":1
          },
          {
            "name":"croconaw",
            "x":1,
            "y":3
          },
          {
            "name":"lombre",
            "x":2,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 4,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"wartortle",
            "x":2,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":3
          },
          {
            "name":"marill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":1
          },
          {
            "name":"croconaw",
            "x":1,
            "y":3
          },
          {
            "name":"lombre",
            "x":2,
            "y":1
          },
          {
            "name":"prinplup",
            "x":3,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 5,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"wartortle",
            "x":2,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":3
          },
          {
            "name":"marill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":1
          },
          {
            "name":"croconaw",
            "x":1,
            "y":3
          },
          {
            "name":"lombre",
            "x":2,
            "y":1
          },
          {
            "name":"prinplup",
            "x":3,
            "y":2
          },
          {
            "name":"spheal",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"wartortle",
            "x":2,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":3
          },
          {
            "name":"marill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":1
          },
          {
            "name":"croconaw",
            "x":1,
            "y":3
          },
          {
            "name":"lombre",
            "x":2,
            "y":1
          },
          {
            "name":"prinplup",
            "x":3,
            "y":2
          },
          {
            "name":"sealeo",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 5,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"blastoise",
            "x":2,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":3
          },
          {
            "name":"marill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":1
          },
          {
            "name":"croconaw",
            "x":1,
            "y":3
          },
          {
            "name":"lombre",
            "x":2,
            "y":1
          },
          {
            "name":"prinplup",
            "x":3,
            "y":2
          },
          {
            "name":"sealeo",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"blastoise",
            "x":2,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":3
          },
          {
            "name":"azumarill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":1
          },
          {
            "name":"croconaw",
            "x":1,
            "y":3
          },
          {
            "name":"lombre",
            "x":2,
            "y":1
          },
          {
            "name":"prinplup",
            "x":3,
            "y":2
          },
          {
            "name":"sealeo",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"blastoise",
            "x":2,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":3
          },
          {
            "name":"azumarill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":1
          },
          {
            "name":"croconaw",
            "x":1,
            "y":3
          },
          {
            "name":"lombre",
            "x":2,
            "y":1
          },
          {
            "name":"empoleon",
            "x":3,
            "y":2
          },
          {
            "name":"sealeo",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"blastoise",
            "x":2,
            "y":2
          },
          {
            "name":"marshtomp",
            "x":2,
            "y":3
          },
          {
            "name":"azumarill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":1
          },
          {
            "name":"feraligatr",
            "x":1,
            "y":3
          },
          {
            "name":"lombre",
            "x":2,
            "y":1
          },
          {
            "name":"empoleon",
            "x":3,
            "y":2
          },
          {
            "name":"sealeo",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"blastoise",
            "x":2,
            "y":2
          },
          {
            "name":"swampert",
            "x":2,
            "y":3
          },
          {
            "name":"azumarill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":1
          },
          {
            "name":"feraligatr",
            "x":1,
            "y":3
          },
          {
            "name":"lombre",
            "x":2,
            "y":1
          },
          {
            "name":"empoleon",
            "x":3,
            "y":2
          },
          {
            "name":"sealeo",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"blastoise",
            "x":2,
            "y":2
          },
          {
            "name":"swampert",
            "x":2,
            "y":3
          },
          {
            "name":"azumarill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwhirl",
            "x":1,
            "y":1
          },
          {
            "name":"feraligatr",
            "x":1,
            "y":3
          },
          {
            "name":"ludicolo",
            "x":2,
            "y":1
          },
          {
            "name":"empoleon",
            "x":3,
            "y":2
          },
          {
            "name":"sealeo",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"seadra",
            "x":0,
            "y":1
          },
          {
            "name":"blastoise",
            "x":2,
            "y":2
          },
          {
            "name":"swampert",
            "x":2,
            "y":3
          },
          {
            "name":"azumarill",
            "x":1,
            "y":2
          },
          {
            "name":"poliwrath",
            "x":1,
            "y":1
          },
          {
            "name":"feraligatr",
            "x":1,
            "y":3
          },
          {
            "name":"ludicolo",
            "x":2,
            "y":1
          },
          {
            "name":"empoleon",
            "x":3,
            "y":2
          },
          {
            "name":"sealeo",
            "x":0,
            "y":2
          }
        ]
      }
    ]
  },
  "FIRE1": {
    "steps": [
      {
        "roundsRequired": 0,
        "board": [
          {
            "name":"igglybuff",
            "x":3,
            "y":2
          },
          {
            "name":"igglybuff",
            "x":4,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"igglybuff",
            "x":4,
            "y":1
          },
          {
            "name":"azurill",
            "x":3,
            "y":1
          },
          {
            "name":"cleffa",
            "x":4,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"cyndaquil",
            "x":5,
            "y":1
          },
          {
            "name":"charmander",
            "x":3,
            "y":3
          },
          {
            "name":"chimchar",
            "x":4,
            "y":3
          },
          {
            "name":"torchic",
            "x":5,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"cyndaquil",
            "x":4,
            "y":1
          },
          {
            "name":"charmeleon",
            "x":5,
            "y":3
          },
          {
            "name":"chimchar",
            "x":4,
            "y":3
          },
          {
            "name":"torchic",
            "x":3,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"cyndaquil",
            "x":4,
            "y":1
          },
          {
            "name":"charmeleon",
            "x":5,
            "y":3
          },
          {
            "name":"chimchar",
            "x":4,
            "y":3
          },
          {
            "name":"torchic",
            "x":3,
            "y":3
          },
          {
            "name":"flareon",
            "x":2,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"quilava",
            "x":4,
            "y":1
          },
          {
            "name":"charmeleon",
            "x":5,
            "y":3
          },
          {
            "name":"chimchar",
            "x":4,
            "y":3
          },
          {
            "name":"torchic",
            "x":3,
            "y":3
          },
          {
            "name":"flareon",
            "x":2,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"quilava",
            "x":4,
            "y":1
          },
          {
            "name":"charmeleon",
            "x":5,
            "y":3
          },
          {
            "name":"chimchar",
            "x":4,
            "y":3
          },
          {
            "name":"combusken",
            "x":3,
            "y":3
          },
          {
            "name":"flareon",
            "x":2,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"quilava",
            "x":2,
            "y":1
          },
          {
            "name":"charmeleon",
            "x":0,
            "y":3
          },
          {
            "name":"chimchar",
            "x":1,
            "y":3
          },
          {
            "name":"combusken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machop",
            "x":4,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"quilava",
            "x":2,
            "y":1
          },
          {
            "name":"charmeleon",
            "x":0,
            "y":3
          },
          {
            "name":"monferno",
            "x":1,
            "y":3
          },
          {
            "name":"combusken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machop",
            "x":4,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 6,
        "board":
        [
          {
            "name":"quilava",
            "x":2,
            "y":1
          },
          {
            "name":"charmeleon",
            "x":0,
            "y":3
          },
          {
            "name":"monferno",
            "x":1,
            "y":3
          },
          {
            "name":"combusken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machop",
            "x":4,
            "y":3
          },
          {
            "name":"magby",
            "x":1,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 4,
        "board":
        [
          {
            "name":"quilava",
            "x":2,
            "y":1
          },
          {
            "name":"charmeleon",
            "x":0,
            "y":3
          },
          {
            "name":"infernape",
            "x":1,
            "y":3
          },
          {
            "name":"blaziken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machoke",
            "x":4,
            "y":3
          },
          {
            "name":"magby",
            "x":1,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 6,
        "board":
        [
          {
            "name":"quilava",
            "x":2,
            "y":1
          },
          {
            "name":"charmeleon",
            "x":0,
            "y":3
          },
          {
            "name":"infernape",
            "x":1,
            "y":3
          },
          {
            "name":"blaziken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machoke",
            "x":4,
            "y":3
          },
          {
            "name":"magmar",
            "x":1,
            "y":1
          },
          {
            "name":"numel",
            "x":5,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"quilava",
            "x":1,
            "y":1
          },
          {
            "name":"charmeleon",
            "x":0,
            "y":3
          },
          {
            "name":"infernape",
            "x":1,
            "y":3
          },
          {
            "name":"blaziken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machoke",
            "x":4,
            "y":3
          },
          {
            "name":"magmar",
            "x":3,
            "y":1
          },
          {
            "name":"numel",
            "x":5,
            "y":3
          },
          {
            "name":"riolu",
            "x":2,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 6,
        "board":
        [
          {
            "name":"quilava",
            "x":1,
            "y":1
          },
          {
            "name":"charizard",
            "x":0,
            "y":3
          },
          {
            "name":"infernape",
            "x":1,
            "y":3
          },
          {
            "name":"blaziken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machoke",
            "x":4,
            "y":3
          },
          {
            "name":"magmar",
            "x":3,
            "y":1
          },
          {
            "name":"numel",
            "x":5,
            "y":3
          },
          {
            "name":"riolu",
            "x":2,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"quilava",
            "x":1,
            "y":1
          },
          {
            "name":"charizard",
            "x":0,
            "y":3
          },
          {
            "name":"infernape",
            "x":1,
            "y":3
          },
          {
            "name":"blaziken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machoke",
            "x":4,
            "y":3
          },
          {
            "name":"magmar",
            "x":3,
            "y":1
          },
          {
            "name":"camerupt",
            "x":5,
            "y":3
          },
          {
            "name":"riolu",
            "x":2,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"quilava",
            "x":1,
            "y":1
          },
          {
            "name":"charizard",
            "x":0,
            "y":3
          },
          {
            "name":"infernape",
            "x":1,
            "y":3
          },
          {
            "name":"blaziken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machoke",
            "x":4,
            "y":3
          },
          {
            "name":"magmar",
            "x":3,
            "y":1
          },
          {
            "name":"camerupt",
            "x":5,
            "y":3
          },
          {
            "name":"lucario",
            "x":2,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"typhlosion",
            "x":1,
            "y":1
          },
          {
            "name":"charizard",
            "x":0,
            "y":3
          },
          {
            "name":"infernape",
            "x":1,
            "y":3
          },
          {
            "name":"blaziken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machoke",
            "x":4,
            "y":3
          },
          {
            "name":"magmar",
            "x":3,
            "y":1
          },
          {
            "name":"camerupt",
            "x":5,
            "y":3
          },
          {
            "name":"lucario",
            "x":2,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"typhlosion",
            "x":1,
            "y":1
          },
          {
            "name":"charizard",
            "x":0,
            "y":3
          },
          {
            "name":"infernape",
            "x":1,
            "y":3
          },
          {
            "name":"blaziken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machamp",
            "x":4,
            "y":3
          },
          {
            "name":"magmar",
            "x":3,
            "y":1
          },
          {
            "name":"camerupt",
            "x":5,
            "y":3
          },
          {
            "name":"lucario",
            "x":2,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"typhlosion",
            "x":1,
            "y":1
          },
          {
            "name":"charizard",
            "x":0,
            "y":3
          },
          {
            "name":"infernape",
            "x":1,
            "y":3
          },
          {
            "name":"blaziken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machamp",
            "x":4,
            "y":3
          },
          {
            "name":"magmortar",
            "x":3,
            "y":1
          },
          {
            "name":"camerupt",
            "x":5,
            "y":3
          },
          {
            "name":"lucario",
            "x":2,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"typhlosion",
            "x":1,
            "y":1
          },
          {
            "name":"charizard",
            "x":0,
            "y":3
          },
          {
            "name":"infernape",
            "x":1,
            "y":3
          },
          {
            "name":"blaziken",
            "x":2,
            "y":3
          },
          {
            "name":"flareon",
            "x":3,
            "y":3
          },
          {
            "name":"machamp",
            "x":4,
            "y":3
          },
          {
            "name":"magmortar",
            "x":3,
            "y":1
          },
          {
            "name":"megacamerupt",
            "x":5,
            "y":3
          },
          {
            "name":"lucario",
            "x":2,
            "y":1
          }
        ]
      }
    ]
  },
  "POISON1": {
    "steps": [
      {
        "roundsRequired": 0,
        "board": [
          {
            "name":"zubat",
            "x":3,
            "y":2
          },
          {
            "name":"geodude",
            "x":4,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"zubat",
            "x":4,
            "y":1
          },
          {
            "name":"geodude",
            "x":3,
            "y":1
          },
          {
            "name":"weedle",
            "x":4,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"zubat",
            "x":5,
            "y":1
          },
          {
            "name":"weedle",
            "x":3,
            "y":3
          },
          {
            "name":"nidoranF",
            "x":4,
            "y":3
          },
          {
            "name":"nidoranM",
            "x":5,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"golbat",
            "x":4,
            "y":1
          },
          {
            "name":"weedle",
            "x":5,
            "y":3
          },
          {
            "name":"nidoranF",
            "x":4,
            "y":3
          },
          {
            "name":"nidoranM",
            "x":3,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"golbat",
            "x":4,
            "y":1
          },
          {
            "name":"weedle",
            "x":5,
            "y":3
          },
          {
            "name":"nidoranF",
            "x":4,
            "y":3
          },
          {
            "name":"nidoranM",
            "x":3,
            "y":3
          },
          {
            "name":"bulbasaur",
            "x":2,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"golbat",
            "x":4,
            "y":1
          },
          {
            "name":"weedle",
            "x":5,
            "y":3
          },
          {
            "name":"nidoranF",
            "x":4,
            "y":3
          },
          {
            "name":"nidoranM",
            "x":3,
            "y":3
          },
          {
            "name":"ivysaur",
            "x":2,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"golbat",
            "x":4,
            "y":1
          },
          {
            "name":"weedle",
            "x":5,
            "y":3
          },
          {
            "name":"nidorina",
            "x":4,
            "y":3
          },
          {
            "name":"nidorino",
            "x":3,
            "y":3
          },
          {
            "name":"ivysaur",
            "x":2,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"golbat",
            "x":2,
            "y":1
          },
          {
            "name":"weedle",
            "x":0,
            "y":3
          },
          {
            "name":"nidorina",
            "x":1,
            "y":3
          },
          {
            "name":"nidorino",
            "x":2,
            "y":3
          },
          {
            "name":"ivysaur",
            "x":3,
            "y":3
          },
          {
            "name":"gastly",
            "x":4,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"golbat",
            "x":2,
            "y":1
          },
          {
            "name":"kakuna",
            "x":0,
            "y":3
          },
          {
            "name":"nidorina",
            "x":1,
            "y":3
          },
          {
            "name":"nidorino",
            "x":2,
            "y":3
          },
          {
            "name":"ivysaur",
            "x":3,
            "y":3
          },
          {
            "name":"gastly",
            "x":4,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 4,
        "board":
        [
          {
            "name":"golbat",
            "x":2,
            "y":1
          },
          {
            "name":"kakuna",
            "x":0,
            "y":3
          },
          {
            "name":"nidorina",
            "x":1,
            "y":3
          },
          {
            "name":"nidorino",
            "x":2,
            "y":3
          },
          {
            "name":"ivysaur",
            "x":3,
            "y":3
          },
          {
            "name":"gastly",
            "x":4,
            "y":1
          },
          {
            "name":"duskull",
            "x":1,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 4,
        "board":
        [
          {
            "name":"golbat",
            "x":2,
            "y":1
          },
          {
            "name":"kakuna",
            "x":0,
            "y":3
          },
          {
            "name":"nidorina",
            "x":1,
            "y":3
          },
          {
            "name":"nidorino",
            "x":2,
            "y":3
          },
          {
            "name":"ivysaur",
            "x":3,
            "y":3
          },
          {
            "name":"gastly",
            "x":4,
            "y":1
          },
          {
            "name":"dusclops",
            "x":1,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 5,
        "board":
        [
          {
            "name":"crobat",
            "x":2,
            "y":1
          },
          {
            "name":"kakuna",
            "x":0,
            "y":3
          },
          {
            "name":"nidorina",
            "x":1,
            "y":3
          },
          {
            "name":"nidorino",
            "x":2,
            "y":3
          },
          {
            "name":"ivysaur",
            "x":3,
            "y":3
          },
          {
            "name":"haunter",
            "x":4,
            "y":1
          },
          {
            "name":"dusclops",
            "x":1,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"crobat",
            "x":2,
            "y":1
          },
          {
            "name":"kakuna",
            "x":0,
            "y":3
          },
          {
            "name":"nidorina",
            "x":1,
            "y":3
          },
          {
            "name":"nidorino",
            "x":2,
            "y":3
          },
          {
            "name":"ivysaur",
            "x":3,
            "y":3
          },
          {
            "name":"haunter",
            "x":4,
            "y":1
          },
          {
            "name":"dusclops",
            "x":1,
            "y":1
          },
          {
            "name":"ralts",
            "x":3,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 5,
        "board":
        [
          {
            "name":"crobat",
            "x":2,
            "y":1
          },
          {
            "name":"kakuna",
            "x":0,
            "y":3
          },
          {
            "name":"nidorina",
            "x":1,
            "y":3
          },
          {
            "name":"nidorino",
            "x":2,
            "y":3
          },
          {
            "name":"ivysaur",
            "x":3,
            "y":3
          },
          {
            "name":"haunter",
            "x":4,
            "y":1
          },
          {
            "name":"dusclops",
            "x":1,
            "y":1
          },
          {
            "name":"kirlia",
            "x":3,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 4,
        "board":
        [
          {
            "name":"crobat",
            "x":2,
            "y":1
          },
          {
            "name":"beedrill",
            "x":0,
            "y":3
          },
          {
            "name":"nidorina",
            "x":1,
            "y":3
          },
          {
            "name":"nidorino",
            "x":2,
            "y":3
          },
          {
            "name":"ivysaur",
            "x":3,
            "y":3
          },
          {
            "name":"haunter",
            "x":4,
            "y":1
          },
          {
            "name":"dusclops",
            "x":1,
            "y":1
          },
          {
            "name":"gardevoir",
            "x":3,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"crobat",
            "x":2,
            "y":1
          },
          {
            "name":"beedrill",
            "x":0,
            "y":3
          },
          {
            "name":"nidorina",
            "x":1,
            "y":3
          },
          {
            "name":"nidorino",
            "x":2,
            "y":3
          },
          {
            "name":"venusaur",
            "x":3,
            "y":3
          },
          {
            "name":"haunter",
            "x":4,
            "y":1
          },
          {
            "name":"dusclops",
            "x":1,
            "y":1
          },
          {
            "name":"gardevoir",
            "x":3,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"crobat",
            "x":2,
            "y":1
          },
          {
            "name":"beedrill",
            "x":0,
            "y":3
          },
          {
            "name":"nidoqueen",
            "x":1,
            "y":3
          },
          {
            "name":"nidorino",
            "x":2,
            "y":3
          },
          {
            "name":"venusaur",
            "x":3,
            "y":3
          },
          {
            "name":"haunter",
            "x":4,
            "y":1
          },
          {
            "name":"dusclops",
            "x":1,
            "y":1
          },
          {
            "name":"gardevoir",
            "x":3,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"crobat",
            "x":2,
            "y":1
          },
          {
            "name":"beedrill",
            "x":0,
            "y":3
          },
          {
            "name":"nidoqueen",
            "x":1,
            "y":3
          },
          {
            "name":"nidorino",
            "x":2,
            "y":3
          },
          {
            "name":"venusaur",
            "x":3,
            "y":3
          },
          {
            "name":"haunter",
            "x":4,
            "y":1
          },
          {
            "name":"dusclops",
            "x":1,
            "y":1
          },
          {
            "name":"gardevoir",
            "x":3,
            "y":1
          },
          {
            "name":"bayleef",
            "x":5,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"crobat",
            "x":2,
            "y":1
          },
          {
            "name":"beedrill",
            "x":0,
            "y":3
          },
          {
            "name":"nidoqueen",
            "x":1,
            "y":3
          },
          {
            "name":"nidoking",
            "x":2,
            "y":3
          },
          {
            "name":"venusaur",
            "x":3,
            "y":3
          },
          {
            "name":"haunter",
            "x":4,
            "y":1
          },
          {
            "name":"dusclops",
            "x":1,
            "y":1
          },
          {
            "name":"gardevoir",
            "x":3,
            "y":1
          },
          {
            "name":"bayleef",
            "x":5,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"crobat",
            "x":2,
            "y":1
          },
          {
            "name":"beedrill",
            "x":0,
            "y":3
          },
          {
            "name":"nidoqueen",
            "x":1,
            "y":3
          },
          {
            "name":"nidoking",
            "x":2,
            "y":3
          },
          {
            "name":"venusaur",
            "x":3,
            "y":3
          },
          {
            "name":"gengar",
            "x":4,
            "y":1
          },
          {
            "name":"dusclops",
            "x":1,
            "y":1
          },
          {
            "name":"gardevoir",
            "x":3,
            "y":1
          },
          {
            "name":"meganium",
            "x":5,
            "y":3
          }
        ]
      }
    ]
  },
  "GROUND1": {
    "steps": [
      {
        "roundsRequired": 0,
        "board": [
          {
            "name":"mareep",
            "x":3,
            "y":2
          },
          {
            "name":"geodude",
            "x":4,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"mareep",
            "x":4,
            "y":1
          },
          {
            "name":"geodude",
            "x":3,
            "y":1
          },
          {
            "name":"turtwig",
            "x":4,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"rhyhorn",
            "x":2,
            "y":3
          },
          {
            "name":"mudkip",
            "x":3,
            "y":3
          },
          {
            "name":"geodude",
            "x":4,
            "y":3
          },
          {
            "name":"turtwig",
            "x":5,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"rhyhorn",
            "x":2,
            "y":3
          },
          {
            "name":"mudkip",
            "x":3,
            "y":3
          },
          {
            "name":"graveler",
            "x":4,
            "y":3
          },
          {
            "name":"turtwig",
            "x":5,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"rhyhorn",
            "x":2,
            "y":3
          },
          {
            "name":"mudkip",
            "x":3,
            "y":3
          },
          {
            "name":"graveler",
            "x":4,
            "y":3
          },
          {
            "name":"turtwig",
            "x":5,
            "y":3
          },
          {
            "name":"aron",
            "x":1,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"rhyhorn",
            "x":2,
            "y":3
          },
          {
            "name":"mudkip",
            "x":3,
            "y":3
          },
          {
            "name":"graveler",
            "x":4,
            "y":3
          },
          {
            "name":"grotle",
            "x":5,
            "y":3
          },
          {
            "name":"aron",
            "x":1,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"rhyhorn",
            "x":2,
            "y":3
          },
          {
            "name":"marshtomp",
            "x":3,
            "y":3
          },
          {
            "name":"graveler",
            "x":4,
            "y":3
          },
          {
            "name":"grotle",
            "x":5,
            "y":3
          },
          {
            "name":"aron",
            "x":1,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"rhydon",
            "x":2,
            "y":3
          },
          {
            "name":"marshtomp",
            "x":3,
            "y":3
          },
          {
            "name":"graveler",
            "x":4,
            "y":3
          },
          {
            "name":"grotle",
            "x":5,
            "y":3
          },
          {
            "name":"aron",
            "x":1,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"rhydon",
            "x":2,
            "y":3
          },
          {
            "name":"marshtomp",
            "x":3,
            "y":3
          },
          {
            "name":"graveler",
            "x":4,
            "y":3
          },
          {
            "name":"grotle",
            "x":5,
            "y":3
          },
          {
            "name":"trapinch",
            "x":1,
            "y":3
          },
          {
            "name":"gible",
            "x":6,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"rhydon",
            "x":2,
            "y":3
          },
          {
            "name":"marshtomp",
            "x":3,
            "y":3
          },
          {
            "name":"graveler",
            "x":4,
            "y":3
          },
          {
            "name":"grotle",
            "x":5,
            "y":3
          },
          {
            "name":"trapinch",
            "x":1,
            "y":3
          },
          {
            "name":"gible",
            "x":6,
            "y":3
          },
          {
            "name":"aron",
            "x":0,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"rhydon",
            "x":2,
            "y":3
          },
          {
            "name":"marshtomp",
            "x":3,
            "y":3
          },
          {
            "name":"graveler",
            "x":4,
            "y":3
          },
          {
            "name":"grotle",
            "x":5,
            "y":3
          },
          {
            "name":"vibrava",
            "x":1,
            "y":3
          },
          {
            "name":"gible",
            "x":6,
            "y":3
          },
          {
            "name":"aron",
            "x":0,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 4,
        "board":
        [
          {
            "name":"rhydon",
            "x":2,
            "y":3
          },
          {
            "name":"marshtomp",
            "x":3,
            "y":3
          },
          {
            "name":"graveler",
            "x":4,
            "y":3
          },
          {
            "name":"grotle",
            "x":5,
            "y":3
          },
          {
            "name":"vibrava",
            "x":1,
            "y":3
          },
          {
            "name":"gible",
            "x":6,
            "y":3
          },
          {
            "name":"lairon",
            "x":0,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"rhydon",
            "x":2,
            "y":3
          },
          {
            "name":"marshtomp",
            "x":3,
            "y":3
          },
          {
            "name":"graveler",
            "x":4,
            "y":3
          },
          {
            "name":"grotle",
            "x":5,
            "y":3
          },
          {
            "name":"vibrava",
            "x":1,
            "y":3
          },
          {
            "name":"gabite",
            "x":6,
            "y":3
          },
          {
            "name":"lairon",
            "x":0,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 4,
        "board":
        [
          {
            "name":"rhydon",
            "x":2,
            "y":3
          },
          {
            "name":"marshtomp",
            "x":3,
            "y":3
          },
          {
            "name":"graveler",
            "x":4,
            "y":3
          },
          {
            "name":"grotle",
            "x":5,
            "y":3
          },
          {
            "name":"vibrava",
            "x":1,
            "y":3
          },
          {
            "name":"gabite",
            "x":6,
            "y":3
          },
          {
            "name":"lairon",
            "x":0,
            "y":3
          },
          {
            "name":"larvitar",
            "x":7,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"rhydon",
            "x":2,
            "y":3
          },
          {
            "name":"marshtomp",
            "x":3,
            "y":3
          },
          {
            "name":"graveler",
            "x":4,
            "y":3
          },
          {
            "name":"grotle",
            "x":5,
            "y":3
          },
          {
            "name":"vibrava",
            "x":1,
            "y":3
          },
          {
            "name":"gabite",
            "x":6,
            "y":3
          },
          {
            "name":"lairon",
            "x":0,
            "y":3
          },
          {
            "name":"pupitar",
            "x":7,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"rhydon",
            "x":2,
            "y":3
          },
          {
            "name":"marshtomp",
            "x":3,
            "y":3
          },
          {
            "name":"golem",
            "x":4,
            "y":3
          },
          {
            "name":"grotle",
            "x":5,
            "y":3
          },
          {
            "name":"vibrava",
            "x":1,
            "y":3
          },
          {
            "name":"gabite",
            "x":6,
            "y":3
          },
          {
            "name":"lairon",
            "x":0,
            "y":3
          },
          {
            "name":"pupitar",
            "x":7,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"rhydon",
            "x":2,
            "y":3
          },
          {
            "name":"swampert",
            "x":3,
            "y":3
          },
          {
            "name":"golem",
            "x":4,
            "y":3
          },
          {
            "name":"torterra",
            "x":5,
            "y":3
          },
          {
            "name":"vibrava",
            "x":1,
            "y":3
          },
          {
            "name":"gabite",
            "x":6,
            "y":3
          },
          {
            "name":"lairon",
            "x":0,
            "y":3
          },
          {
            "name":"pupitar",
            "x":7,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"rhydon",
            "x":2,
            "y":3
          },
          {
            "name":"swampert",
            "x":3,
            "y":3
          },
          {
            "name":"golem",
            "x":4,
            "y":3
          },
          {
            "name":"torterra",
            "x":5,
            "y":3
          },
          {
            "name":"vibrava",
            "x":1,
            "y":3
          },
          {
            "name":"gabite",
            "x":6,
            "y":3
          },
          {
            "name":"lairon",
            "x":0,
            "y":3
          },
          {
            "name":"pupitar",
            "x":7,
            "y":3
          },
          {
            "name":"onix",
            "x":7,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"rhydon",
            "x":2,
            "y":3
          },
          {
            "name":"swampert",
            "x":3,
            "y":3
          },
          {
            "name":"golem",
            "x":4,
            "y":3
          },
          {
            "name":"torterra",
            "x":5,
            "y":3
          },
          {
            "name":"vibrava",
            "x":1,
            "y":3
          },
          {
            "name":"gabite",
            "x":6,
            "y":3
          },
          {
            "name":"lairon",
            "x":0,
            "y":3
          },
          {
            "name":"pupitar",
            "x":7,
            "y":3
          },
          {
            "name":"steelix",
            "x":7,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"rhyperior",
            "x":2,
            "y":3
          },
          {
            "name":"swampert",
            "x":3,
            "y":3
          },
          {
            "name":"golem",
            "x":4,
            "y":3
          },
          {
            "name":"torterra",
            "x":5,
            "y":3
          },
          {
            "name":"vibrava",
            "x":1,
            "y":3
          },
          {
            "name":"gabite",
            "x":6,
            "y":3
          },
          {
            "name":"lairon",
            "x":0,
            "y":3
          },
          {
            "name":"tyranitar",
            "x":7,
            "y":3
          },
          {
            "name":"mega-steelix",
            "x":7,
            "y":2
          }
        ]
      }
    ]
  },
  "NORMAL1": {
    "steps": [
      {
        "roundsRequired": 0,
        "board": [
          {
            "name":"igglybuff",
            "x":3,
            "y":2
          },
          {
            "name":"cleffa",
            "x":4,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"cleffa",
            "x":4,
            "y":1
          },
          {
            "name":"jigglypuff",
            "x":3,
            "y":1
          },
          {
            "name":"azurill",
            "x":4,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"cleffa",
            "x":5,
            "y":1
          },
          {
            "name":"jigglypuff",
            "x":4,
            "y":2
          },
          {
            "name":"marill",
            "x":4,
            "y":3
          },
          {
            "name":"eevee",
            "x":5,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"clefairy",
            "x":4,
            "y":1
          },
          {
            "name":"jigglypuff",
            "x":4,
            "y":2
          },
          {
            "name":"marill",
            "x":4,
            "y":3
          },
          {
            "name":"sylveon",
            "x":3,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"clefairy",
            "x":4,
            "y":1
          },
          {
            "name":"jigglypuff",
            "x":4,
            "y":2
          },
          {
            "name":"marill",
            "x":4,
            "y":3
          },
          {
            "name":"sylveon",
            "x":3,
            "y":2
          },
          {
            "name":"pichu",
            "x":3,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"clefairy",
            "x":4,
            "y":1
          },
          {
            "name":"jigglypuff",
            "x":4,
            "y":2
          },
          {
            "name":"sylveon",
            "x":4,
            "y":3
          },
          {
            "name":"marill",
            "x":3,
            "y":2
          },
          {
            "name":"pichu",
            "x":3,
            "y":3
          },
          {
            "name":"togepi",
            "x":3,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"clefairy",
            "x":4,
            "y":1
          },
          {
            "name":"jigglypuff",
            "x":4,
            "y":2
          },
          {
            "name":"sylveon",
            "x":4,
            "y":3
          },
          {
            "name":"marill",
            "x":3,
            "y":2
          },
          {
            "name":"pichu",
            "x":3,
            "y":3
          },
          {
            "name":"togetic",
            "x":3,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"clefairy",
            "x":4,
            "y":1
          },
          {
            "name":"jigglypuff",
            "x":4,
            "y":2
          },
          {
            "name":"sylveon",
            "x":4,
            "y":3
          },
          {
            "name":"marill",
            "x":3,
            "y":2
          },
          {
            "name":"pichu",
            "x":3,
            "y":3
          },
          {
            "name":"togetic",
            "x":3,
            "y":1
          },
          {
            "name":"slakoth",
            "x":4,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"clefairy",
            "x":4,
            "y":1
          },
          {
            "name":"jigglypuff",
            "x":4,
            "y":2
          },
          {
            "name":"sylveon",
            "x":4,
            "y":3
          },
          {
            "name":"marill",
            "x":3,
            "y":2
          },
          {
            "name":"pikachu",
            "x":3,
            "y":1
          },
          {
            "name":"togetic",
            "x":2,
            "y":1
          },
          {
            "name":"slakoth",
            "x":3,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 4,
        "board":
        [
          {
            "name":"clefairy",
            "x":4,
            "y":1
          },
          {
            "name":"wigglytuff",
            "x":4,
            "y":2
          },
          {
            "name":"sylveon",
            "x":4,
            "y":3
          },
          {
            "name":"azumarill",
            "x":3,
            "y":2
          },
          {
            "name":"pikachu",
            "x":3,
            "y":1
          },
          {
            "name":"togetic",
            "x":2,
            "y":1
          },
          {
            "name":"vigoroth",
            "x":3,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 4,
        "board":
        [
          {
            "name":"clefairy",
            "x":4,
            "y":1
          },
          {
            "name":"wigglytuff",
            "x":4,
            "y":2
          },
          {
            "name":"sylveon",
            "x":4,
            "y":3
          },
          {
            "name":"azumarill",
            "x":3,
            "y":2
          },
          {
            "name":"raichu",
            "x":3,
            "y":1
          },
          {
            "name":"togekiss",
            "x":2,
            "y":1
          },
          {
            "name":"vigoroth",
            "x":3,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 5,
        "board":
        [
          {
            "name":"clefairy",
            "x":4,
            "y":1
          },
          {
            "name":"wigglytuff",
            "x":4,
            "y":2
          },
          {
            "name":"sylveon",
            "x":4,
            "y":3
          },
          {
            "name":"azumarill",
            "x":3,
            "y":2
          },
          {
            "name":"raichu",
            "x":3,
            "y":1
          },
          {
            "name":"togekiss",
            "x":2,
            "y":1
          },
          {
            "name":"slaking",
            "x":3,
            "y":3
          },
          {
            "name":"luxio",
            "x":2,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"clefairy",
            "x":4,
            "y":1
          },
          {
            "name":"wigglytuff",
            "x":4,
            "y":2
          },
          {
            "name":"sylveon",
            "x":4,
            "y":3
          },
          {
            "name":"azumarill",
            "x":3,
            "y":2
          },
          {
            "name":"raichu",
            "x":3,
            "y":1
          },
          {
            "name":"togekiss",
            "x":2,
            "y":1
          },
          {
            "name":"slaking",
            "x":3,
            "y":3
          },
          {
            "name":"luxray",
            "x":2,
            "y":2
          },
          {
            "name":"elekid",
            "x":1,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 5,
        "board":
        [
          {
            "name":"clefairy",
            "x":4,
            "y":1
          },
          {
            "name":"wigglytuff",
            "x":4,
            "y":2
          },
          {
            "name":"sylveon",
            "x":4,
            "y":3
          },
          {
            "name":"azumarill",
            "x":3,
            "y":2
          },
          {
            "name":"raichu",
            "x":3,
            "y":1
          },
          {
            "name":"togekiss",
            "x":2,
            "y":1
          },
          {
            "name":"slaking",
            "x":3,
            "y":3
          },
          {
            "name":"luxray",
            "x":2,
            "y":2
          },
          {
            "name":"electabuzz",
            "x":1,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"clefairy",
            "x":4,
            "y":1
          },
          {
            "name":"wigglytuff",
            "x":4,
            "y":2
          },
          {
            "name":"sylveon",
            "x":4,
            "y":3
          },
          {
            "name":"azumarill",
            "x":3,
            "y":2
          },
          {
            "name":"raichu",
            "x":3,
            "y":1
          },
          {
            "name":"togekiss",
            "x":2,
            "y":1
          },
          {
            "name":"slaking",
            "x":3,
            "y":3
          },
          {
            "name":"luxray",
            "x":2,
            "y":2
          },
          {
            "name":"electabuzz",
            "x":1,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"clefairy",
            "x":4,
            "y":1
          },
          {
            "name":"wigglytuff",
            "x":4,
            "y":2
          },
          {
            "name":"sylveon",
            "x":4,
            "y":3
          },
          {
            "name":"azumarill",
            "x":3,
            "y":2
          },
          {
            "name":"raichu",
            "x":3,
            "y":1
          },
          {
            "name":"togekiss",
            "x":2,
            "y":1
          },
          {
            "name":"slaking",
            "x":3,
            "y":3
          },
          {
            "name":"luxray",
            "x":2,
            "y":2
          },
          {
            "name":"electabuzz",
            "x":1,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"clefairy",
            "x":4,
            "y":1
          },
          {
            "name":"wigglytuff",
            "x":4,
            "y":2
          },
          {
            "name":"sylveon",
            "x":4,
            "y":3
          },
          {
            "name":"azumarill",
            "x":3,
            "y":2
          },
          {
            "name":"raichu",
            "x":3,
            "y":1
          },
          {
            "name":"togekiss",
            "x":2,
            "y":1
          },
          {
            "name":"slaking",
            "x":3,
            "y":3
          },
          {
            "name":"luxray",
            "x":2,
            "y":2
          },
          {
            "name":"electabuzz",
            "x":1,
            "y":2
          },
          {
            "name":"munchlax",
            "x":1,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"clefairy",
            "x":4,
            "y":1
          },
          {
            "name":"wigglytuff",
            "x":4,
            "y":2
          },
          {
            "name":"sylveon",
            "x":4,
            "y":3
          },
          {
            "name":"azumarill",
            "x":3,
            "y":2
          },
          {
            "name":"raichu",
            "x":3,
            "y":1
          },
          {
            "name":"togekiss",
            "x":2,
            "y":1
          },
          {
            "name":"slaking",
            "x":3,
            "y":3
          },
          {
            "name":"luxray",
            "x":2,
            "y":2
          },
          {
            "name":"electabuzz",
            "x":1,
            "y":2
          },
          {
            "name":"snorlax",
            "x":1,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"clefairy",
            "x":4,
            "y":1
          },
          {
            "name":"wigglytuff",
            "x":4,
            "y":2
          },
          {
            "name":"sylveon",
            "x":4,
            "y":3
          },
          {
            "name":"azumarill",
            "x":3,
            "y":2
          },
          {
            "name":"raichu",
            "x":3,
            "y":1
          },
          {
            "name":"togekiss",
            "x":2,
            "y":1
          },
          {
            "name":"slaking",
            "x":3,
            "y":3
          },
          {
            "name":"luxray",
            "x":2,
            "y":2
          },
          {
            "name":"electabuzz",
            "x":1,
            "y":2
          },
          {
            "name":"snorlax",
            "x":1,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"clefairy",
            "x":4,
            "y":1
          },
          {
            "name":"wigglytuff",
            "x":4,
            "y":2
          },
          {
            "name":"sylveon",
            "x":4,
            "y":3
          },
          {
            "name":"azumarill",
            "x":3,
            "y":2
          },
          {
            "name":"raichu",
            "x":3,
            "y":1
          },
          {
            "name":"togekiss",
            "x":2,
            "y":1
          },
          {
            "name":"slaking",
            "x":3,
            "y":3
          },
          {
            "name":"luxray",
            "x":2,
            "y":2
          },
          {
            "name":"electabuzz",
            "x":1,
            "y":2
          },
          {
            "name":"snorlax",
            "x":1,
            "y":1
          }
        ]
      }
    ]
  },
  "GRASS1": {
    "steps": [
      {
        "roundsRequired": 0,
        "board": [
          {
            "name":"hoppip",
            "x":3,
            "y":2
          },
          {
            "name":"seedot",
            "x":4,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"hoppip",
            "x":4,
            "y":1
          },
          {
            "name":"seedot",
            "x":4,
            "y":3
          },
          {
            "name":"caterpie",
            "x":4,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"skiploom",
            "x":4,
            "y":1
          },
          {
            "name":"seedot",
            "x":4,
            "y":3
          },
          {
            "name":"caterpie",
            "x":4,
            "y":2
          },
          {
            "name":"bulbasaur",
            "x":5,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"skiploom",
            "x":4,
            "y":1
          },
          {
            "name":"nuzleaf",
            "x":4,
            "y":3
          },
          {
            "name":"metapod",
            "x":4,
            "y":2
          },
          {
            "name":"bulbasaur",
            "x":5,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"skiploom",
            "x":4,
            "y":1
          },
          {
            "name":"nuzleaf",
            "x":4,
            "y":3
          },
          {
            "name":"metapod",
            "x":4,
            "y":2
          },
          {
            "name":"bulbasaur",
            "x":5,
            "y":1
          },
          {
            "name":"treecko",
            "x":3,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"skiploom",
            "x":4,
            "y":1
          },
          {
            "name":"nuzleaf",
            "x":4,
            "y":3
          },
          {
            "name":"metapod",
            "x":4,
            "y":2
          },
          {
            "name":"ivysaur",
            "x":5,
            "y":1
          },
          {
            "name":"treecko",
            "x":3,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"skiploom",
            "x":4,
            "y":1
          },
          {
            "name":"nuzleaf",
            "x":4,
            "y":3
          },
          {
            "name":"metapod",
            "x":4,
            "y":2
          },
          {
            "name":"ivysaur",
            "x":5,
            "y":1
          },
          {
            "name":"grovyle",
            "x":3,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"skiploom",
            "x":4,
            "y":1
          },
          {
            "name":"nuzleaf",
            "x":4,
            "y":3
          },
          {
            "name":"metapod",
            "x":4,
            "y":2
          },
          {
            "name":"ivysaur",
            "x":5,
            "y":1
          },
          {
            "name":"grovyle",
            "x":3,
            "y":3
          },
          {
            "name":"chikorita",
            "x":1,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 1,
        "board":
        [
          {
            "name":"skiploom",
            "x":4,
            "y":1
          },
          {
            "name":"nuzleaf",
            "x":4,
            "y":3
          },
          {
            "name":"metapod",
            "x":4,
            "y":2
          },
          {
            "name":"ivysaur",
            "x":5,
            "y":1
          },
          {
            "name":"grovyle",
            "x":3,
            "y":3
          },
          {
            "name":"bayleef",
            "x":1,
            "y":1
          }
        ]
      },
      {
        "roundsRequired": 4,
        "board":
        [
          {
            "name":"skiploom",
            "x":4,
            "y":1
          },
          {
            "name":"nuzleaf",
            "x":4,
            "y":3
          },
          {
            "name":"metapod",
            "x":4,
            "y":2
          },
          {
            "name":"ivysaur",
            "x":5,
            "y":1
          },
          {
            "name":"grovyle",
            "x":3,
            "y":3
          },
          {
            "name":"bayleef",
            "x":1,
            "y":1
          },
          {
            "name":"leafon",
            "x":2,
            "y":3
          }
        ]
      },
      {
        "roundsRequired": 4,
        "board":
        [
          {
            "name":"skiploom",
            "x":4,
            "y":1
          },
          {
            "name":"nuzleaf",
            "x":4,
            "y":3
          },
          {
            "name":"metapod",
            "x":4,
            "y":2
          },
          {
            "name":"ivysaur",
            "x":5,
            "y":1
          },
          {
            "name":"grovyle",
            "x":3,
            "y":3
          },
          {
            "name":"bayleef",
            "x":1,
            "y":1
          },
          {
            "name":"leafon",
            "x":2,
            "y":3
          },
          {
            "name":"turtwig",
            "x":3,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 5,
        "board":
        [
          {
            "name":"skiploom",
            "x":4,
            "y":1
          },
          {
            "name":"nuzleaf",
            "x":4,
            "y":3
          },
          {
            "name":"metapod",
            "x":4,
            "y":2
          },
          {
            "name":"ivysaur",
            "x":5,
            "y":1
          },
          {
            "name":"grovyle",
            "x":3,
            "y":3
          },
          {
            "name":"bayleef",
            "x":1,
            "y":1
          },
          {
            "name":"leafon",
            "x":2,
            "y":3
          },
          {
            "name":"grotle",
            "x":3,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"skiploom",
            "x":4,
            "y":1
          },
          {
            "name":"nuzleaf",
            "x":4,
            "y":3
          },
          {
            "name":"metapod",
            "x":4,
            "y":2
          },
          {
            "name":"ivysaur",
            "x":5,
            "y":1
          },
          {
            "name":"grovyle",
            "x":3,
            "y":3
          },
          {
            "name":"bayleef",
            "x":1,
            "y":1
          },
          {
            "name":"leafon",
            "x":2,
            "y":3
          },
          {
            "name":"grotle",
            "x":3,
            "y":2
          },
          {
            "name":"lotad",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 5,
        "board":
        [
          {
            "name":"skiploom",
            "x":4,
            "y":1
          },
          {
            "name":"nuzleaf",
            "x":4,
            "y":3
          },
          {
            "name":"metapod",
            "x":4,
            "y":2
          },
          {
            "name":"ivysaur",
            "x":5,
            "y":1
          },
          {
            "name":"grovyle",
            "x":3,
            "y":3
          },
          {
            "name":"bayleef",
            "x":1,
            "y":1
          },
          {
            "name":"leafon",
            "x":2,
            "y":3
          },
          {
            "name":"grotle",
            "x":3,
            "y":2
          },
          {
            "name":"lombre",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 2,
        "board":
        [
          {
            "name":"jumpluff",
            "x":4,
            "y":1
          },
          {
            "name":"nuzleaf",
            "x":4,
            "y":3
          },
          {
            "name":"metapod",
            "x":4,
            "y":2
          },
          {
            "name":"ivysaur",
            "x":5,
            "y":1
          },
          {
            "name":"grovyle",
            "x":3,
            "y":3
          },
          {
            "name":"bayleef",
            "x":1,
            "y":1
          },
          {
            "name":"leafon",
            "x":2,
            "y":3
          },
          {
            "name":"grotle",
            "x":3,
            "y":2
          },
          {
            "name":"lombre",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"jumpluff",
            "x":4,
            "y":1
          },
          {
            "name":"shiftry",
            "x":4,
            "y":3
          },
          {
            "name":"metapod",
            "x":4,
            "y":2
          },
          {
            "name":"ivysaur",
            "x":5,
            "y":1
          },
          {
            "name":"grovyle",
            "x":3,
            "y":3
          },
          {
            "name":"bayleef",
            "x":1,
            "y":1
          },
          {
            "name":"leafon",
            "x":2,
            "y":3
          },
          {
            "name":"grotle",
            "x":3,
            "y":2
          },
          {
            "name":"ludicolo",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"jumpluff",
            "x":4,
            "y":1
          },
          {
            "name":"shiftry",
            "x":4,
            "y":3
          },
          {
            "name":"butterfree",
            "x":4,
            "y":2
          },
          {
            "name":"ivysaur",
            "x":5,
            "y":1
          },
          {
            "name":"grovyle",
            "x":3,
            "y":3
          },
          {
            "name":"bayleef",
            "x":1,
            "y":1
          },
          {
            "name":"leafon",
            "x":2,
            "y":3
          },
          {
            "name":"grotle",
            "x":3,
            "y":2
          },
          {
            "name":"ludicolo",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"jumpluff",
            "x":4,
            "y":1
          },
          {
            "name":"shiftry",
            "x":4,
            "y":3
          },
          {
            "name":"butterfree",
            "x":4,
            "y":2
          },
          {
            "name":"venusaur",
            "x":5,
            "y":1
          },
          {
            "name":"grovyle",
            "x":3,
            "y":3
          },
          {
            "name":"bayleef",
            "x":1,
            "y":1
          },
          {
            "name":"leafon",
            "x":2,
            "y":3
          },
          {
            "name":"grotle",
            "x":3,
            "y":2
          },
          {
            "name":"ludicolo",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"jumpluff",
            "x":4,
            "y":1
          },
          {
            "name":"shiftry",
            "x":4,
            "y":3
          },
          {
            "name":"butterfree",
            "x":4,
            "y":2
          },
          {
            "name":"venusaur",
            "x":5,
            "y":1
          },
          {
            "name":"meganium",
            "x":3,
            "y":3
          },
          {
            "name":"sceptile",
            "x":1,
            "y":1
          },
          {
            "name":"leafon",
            "x":2,
            "y":3
          },
          {
            "name":"grotle",
            "x":3,
            "y":2
          },
          {
            "name":"ludicolo",
            "x":0,
            "y":2
          }
        ]
      },
      {
        "roundsRequired": 3,
        "board":
        [
          {
            "name":"jumpluff",
            "x":4,
            "y":1
          },
          {
            "name":"shiftry",
            "x":4,
            "y":3
          },
          {
            "name":"butterfree",
            "x":4,
            "y":2
          },
          {
            "name":"venusaur",
            "x":5,
            "y":1
          },
          {
            "name":"meganium",
            "x":3,
            "y":3
          },
          {
            "name":"sceptile",
            "x":1,
            "y":1
          },
          {
            "name":"leafon",
            "x":2,
            "y":3
          },
          {
            "name":"torterra",
            "x":3,
            "y":2
          },
          {
            "name":"ludicolo",
            "x":0,
            "y":2
          }
        ]
      }
    ]
  }
}


module.exports = SCENARIOS;
